### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by TristanMinor** [armin-pfaeffle/sass-autocompile#1]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
SassAutocompileView.initialize (/Users/tristan/.atom/packages/sass-autocompile/lib/sass-autocompile-view.coffee:21:13)
```

**Comment by armin-pfaeffle** [comment]
Thanks for your report!

I fixed it!
