### ISSUE TITLE
The package works flawlessly, but occasionally leaves an unusable black bar on the bottom of my editor.

### ISSUE THREAD

**Issue by jakedemian** [armin-pfaeffle/sass-autocompile#10]
Sometimes after compiling this package leaves a black bar in its wake on the bottom of my editor.  The only way to get rid of it is to close Atom completely and then reopen it.  Once the black bar appears, the compiler window starts pinning to the black bar instead of to the bottom of the window, meaning that given enough time the black bar will take over the whole editor.  Here's what the bar looks like:

http://i.imgur.com/mR2C711.png

**Comment by armin-pfaeffle** [comment]
Hey!

Looks really interessting... But, I have no idea, where it can come from. Do you have any other packages installed? Can you post them?

When this black panel appears, can you try to hide the panel via `ctrl-alt-shift-h`? Does this work?

**Comment by jakedemian** [comment]
No, the ctrl-alt-shift-h ocmmand does not hide the black bar.  Also, this is the only extension I have installed so far.

**Comment by armin-pfaeffle** [comment]
Another idea would be that it's a theme bug. Can you try changing your theme and test it once again?!

**Comment by jakedemian** [comment]
Okay so a slight update to the problem.  I just noticed that e behavior is slightly different than I described.  Rather than a bar being left every once in a while, every single time my code autocompiles it leaves behind a very small black bar, maybe 3-5 pixels tall.  I just never notice it until it compounds to a noticeable height.

**Comment by jakedemian** [comment]
Okay so I figured something else out.  I closed and reopened atom and compiled one of my sass files to see what happens the first time.  I discovered this line in the auto compile pane is what is causing the trouble:  http://i.imgur.com/iSKq0DY.png

Every time I compile a sass file, that thin line gets left behind.  Over time, it just builds up layer by layer until I begin to notice it.

**Comment by armin-pfaeffle** [comment]
Hm... I can't see the problem. Have you tried changing your theme? What theme do you have installed?

Another idea would be that you test [atom-minify](https://atom.io/packages/atom-minify). The reason for this is, that I'm using the same panel there, but in a newer and improved version. Please install that package and tell me if there is the same problem?

**Comment by jakedemian** [comment]
I'm just using the Atom Dark theme.

And when I installed atom-minify and set it to minify on save, I had the same issue of the black bar being left behind and slowly growing as I continued to use the package.

**Comment by armin-pfaeffle** [comment]
Now I could reproduce that problem and I fixed it with 0.7.3.
