### ISSUE TITLE
Compile choice not working

### ISSUE THREAD

**Issue by ScorpioCoding** [armin-pfaeffle/sass-autocompile#100]
I can't chang the compile choice to anything other than compressed.
I wish to change it extended but nothing happens.

**Comment by monolux** [comment]
How does one actually change the compile choice please?

**Comment by monolux** [comment]
Just had to add ```
// compileExpanded
// compileExpanded: true
``` to the .scss file and got back a normal .css file, seems to work fine. Have you got Node and node-sass installed?

**Comment by monolux** [comment]
And with adding

`// compileExpanded: \css\$1.css`

to the first line of the .scss file I managed to put the uncompressed .css file into the folder css in the root of the project folder.

**Comment by ScorpioCoding** [comment]
Ok got it working  ... thanks

**Comment by ScorpioCoding** [comment]
question..
you've got compressed, expanded and the third one was what again?

**Comment by monolux** [comment]
Glad you got it working!!

Can someone in charge please close this ticket?

**Comment by armin-pfaeffle** [comment]
Hey! Thanks for you support!
