### ISSUE TITLE
Only direct compilation is working.

### ISSUE THREAD

**Issue by mattatt** [armin-pfaeffle/sass-autocompile#107]
I have similar problem to one mentioned before. I installed package and the only way it works is when I manually pick option "Direct compilation" from top menu. 

Compile to file doesn't work, doesn't work when I try compile file from file's context menu and when using shortcuts, not mentioned it doesn't work on save.

I'm not happy with that, I tried reinstalling many times and rechecking options in settings. 

I'm missing something? I really look forward to use sass with autocompile. I'm currently working on my first project with sass and I have big hopes with this package.

**Comment by armin-pfaeffle** [comment]
Can you give me the following version:
- Atom
- node-sass (execute in terminal `node-sass --version`)
- Mac/Win/Linux?

Can you open developer tools and see if there is any error?

**Comment by mattatt** [comment]
Ok, this it weird. After I posted about this problem I decided to uninstall plugin and I switched to Koala. 
Now when you answer I installed plugin once again and it works just fine...  really I have no idea why, but it works right now.

It still might be valuable for you so:
- node-sass       4.5.0   (Wrapper)       [JavaScript]
- libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
- atom 1.14.1
- windows 10 home 
- no errors in console

Using the opportunity of open topic, is there option to compile main sass file when I make changes in partials? eg changes in _header.scss triggers compilation in main.scss ? 

Really I installed this plugin few minutes ago - don't judge me too harsh ;)

**Comment by armin-pfaeffle** [comment]
Well, I really don't know what was the problem. There are more cases where other problems occur and can be solved by reinstall or install package after update... Strange...

Thanks for you information!

Yes! Of course! You should use [main](https://github.com/armin-pfaeffle/sass-autocompile#main) parameter in partial file. Here an example:

**main.scss**
```
// compileCompressed: ../css/main.css
body {
    background-color: red;
}

@import "content/child";
```

**content/_child.scss**
```
// main: ../main.scss
p {
    margin: 10px 0 0 0;
}
```

When you modify _child.scss and save this file, my package reads the **main** paramter and then goes to main.scss and compiles this file.
