### ISSUE TITLE
Output file size is zero bytes

### ISSUE THREAD

**Issue by eduardomart** [armin-pfaeffle/sass-autocompile#108]
I have sass-autocompile set to compile on save. An output css file is created but it's 0kb.

I do have node and sass installed via terminal (OSX)
Any ideas?

Atom 1.14
sass-autocompile 0.13.2
node-sass 4.5.0

**Comment by eduardomart** [comment]
More on this, it appears it's components that don't get compiled.
I am trying to compile **Foundation-Sites-6.3.0**

However if I insert basic bits in `foundation.scss` like `body { background: red }` that's all that is output in the resulting .css file

**Comment by armin-pfaeffle** [comment]
Hey! Have you tried a minimal example? Create the following file `style.scss`:
```
$backgorund-color: red;
body {
    background-color: $background-color;
}
```
And try to compile this file.

Yes, there are frameworks that won't compile. I will check whats the problem with Foundation Sites.
