### ISSUE TITLE
Precision not working

### ISSUE THREAD

**Issue by monolux** [armin-pfaeffle/sass-autocompile#111]
```
.sample {
    width: 33.33333333333333333333333%;
}
```
compiles into 

```
.sample {
	width: 33.33333333333333333333333%;
}
```
despite **Precision** in **Settings/Options** being 3.

Same thing happens with
```
.sample {
    width: 33.33333333333333333333333px;
}
```
, it compiles into the exact same .css as above except for **px** being at the end of the width declaration.

To make sure I have checked that all requirements are installed correctly and can supply logs/versions if you need them.

**Comment by monolux** [comment]
With a simply package.json and few packages I cannot seem to get Precision to work.

Does anyone else see this behaviour?
```
{
  "name": "--",
  "version": "1.0.0",
  "description": "--",
  "main": "Gruntfile.js",
  "author": "--",
  "license": "MIT",
  "devDependencies": {
    "grunt": "^1.0.1",
    "grunt-contrib-cssmin": "^2.0.0",
    "grunt-contrib-uglify": "^2.2.0",
    "grunt-contrib-watch": "^1.0.0",
    "grunt-criticalcss": "^2.1.0",
    "grunt-postcss": "^0.8.0",
    "autoprefixer": "^6.7.7"
  }
}
```
Atom 1.15.0 Windows
NPM 4.4.1
Node 6.9.4
node-sass 4.5.0
libsass 3.5.0.beta.2

**Comment by monolux** [comment]
I confirm this is an error.

Fresh system, fresh install of Atom, node, node-sass and sass-autocompile and the precision setting is not taking affect on any of the compiled files.

**Comment by armin-pfaeffle** [comment]
That's an interessting "bug", but it is not a problem of my package, it's from node-sass. Here an example:
```sass
$width: 1.23456789%

.sample
    height: 33.333333333%
    width: $width
```
... compiling with this command: `node-sass --output-style compressed --precision 3 test.sass test.css` (not compiling by my Atom package!)

Output:css
```
.sample{height:33.333333333%;width:1.235%}
```
And I'm even not sure about that this behaviour is a bug. I think the precision option is only used when values are calculated and *not* when values are fix. See this example:
```sass
.sample
    height: 33.333333333% * 1
```
... compiles to:
```css
.sample{height:33.333%}
```

**Comment by monolux** [comment]
Armin, thank you for your reply, I will look into this from the node-sass way and then confirm my findings with you. Would be great if regardless of node-sass you could implement the precision setting, meaning overriding the results you get from node-sass and thus making precision working as per documentation. Yes I do hear you this is out of the scope of your "wrapper". In that case, otherwise, perhaps remove it from the Options altogether?

**Comment by armin-pfaeffle** [comment]
Hm... Adding this as a separate option would be an idea! I think it would be easy to implement by executing a simpley regular expression. But something like that is already on my _feature list_:  custom filters.

**Comment by monolux** [comment]
Coming back to this, your first example now makes perfect sense, only when a value in a variable is used that needs to be compiled the precision setting will come into action. Fixed values are left alone. Interesting and even more so since you show that by multiplying it by 1 and thus invoking a computation/calculation of the value the precision setting will work. For now this means, if I like to have a uniform precision in the output on fixed values just multiply by 1 and done, values specified by variables will work.

About _custom filters_: How will they work with regards to precision?
