### ISSUE TITLE
changing import files does not update the child css

### ISSUE THREAD

**Issue by claudius25** [armin-pfaeffle/sass-autocompile#114]
So i have a _vars.scss and a child.scss that uses it (@import ../_vars.scss).

When i modify a variable in _vars, it does not end up in child.css?

What am i doing wrong?

**Comment by armin-pfaeffle** [comment]
Use the mian paramter. Set this as first line in your `_vars.scss`, but adjust the path to you `child.scss`.

```scss
// main: child.scss
```

**Comment by claudius25** [comment]
Thank you for the solution, but the project i have is made in angular 2, so i have multiple components, each with one scss file. These files import _vars.scss. How do i propagate each modification of _vars.scss to each child scss. The above solution works only for one file :(

**Comment by armin-pfaeffle** [comment]
I'm sorry, but at the moment, you can compile only one file. The feature "compile multiple files" is one point on my agenda!
