### ISSUE TITLE
Typo when compiling manually

### ISSUE THREAD

**Issue by mokyox** [armin-pfaeffle/sass-autocompile#120]
Hello,

I didn't see the issue here but there's a typo "Is the syntax of your inout SASS or SCSS? when selecting to compile SCSS/Sass manually. 

<img width="717" alt="screen shot 2017-06-25 at 19 37 24" src="https://user-images.githubusercontent.com/23492964/27515449-4aa049aa-59de-11e7-942e-3399c772b099.png">

**Comment by IiroP** [comment]
Should it be "Is the syntax **of** your **input** SASS or SCSS"?
