### ISSUE TITLE
Generated CSS contains spaces in between nested nodes

### ISSUE THREAD

**Issue by rtubio** [armin-pfaeffle/sass-autocompile#123]
The following code in SASS:

    .bib-selectable {
        :hover {
            cursor: pointer;
        }
    }

... generates the following CSS code:

    .bib-selectable :hover {
        cursor: pointer;
    }

Which does not work with either Chrome or Firefox because of the whitespace in between the class and the selector. If I remove the whitespace, it works.

Any suggestions? What might I be doing wrong?

**Comment by rtubio** [comment]
Sorry, I was mixing up SASS with other stuff...

**Comment by armin-pfaeffle** [comment]
Hey! Yes, there was an error in your SASS. Here the correct solution if someone stumbles across this issue. The ampersand before `:hover: is missing.
```sass
.bib-selectable {
    &:hover {
        cursor: pointer;
    }
}
```
Result:
```css
.bib-selectable:hover {
    cursor: pointer;
}
```
