### ISSUE TITLE
Auto Compile main file if another sass file is saved

### ISSUE THREAD

**Issue by christianvsauer** [armin-pfaeffle/sass-autocompile#125]
Hey guys,

I´m new to Sass and currently re-entering web-development, so I hope you can help me out with this one. I´m using Atom with Sass Auto-compile. I have a main sass file that imports other sass files. Is it possible, that whenever I save one of those files (that are imported), the main file is compiled?

Thanks in advance
Christian

**Comment by drumline18** [comment]
It won't do it on it's own.
You need to add a main parameter in the first line of your sass partials to link them back to their main file.

main.scss
```sass
@import "partial"
body{width:$var;}
```
_partial.scss
```sass
//main:main.scss
$var : 100%
```

(unless my info is outdated)

**Comment by christianvsauer** [comment]
Thank you so much.

Best regards
Chris
