### ISSUE TITLE
@import unsupported

### ISSUE THREAD

**Issue by fxmountain** [armin-pfaeffle/sass-autocompile#128]
If you use @import in an .scss file you get a second .css (.min.css) file not one (like @import is used).

**Comment by fxmountain** [comment]
Main style sheet: "style.scss"
In that stylesheet: "@import 'desktop.scss';"

Compiled output: style.min.css (without desktop.scss) & desktop.min.css as a seperate file.

**Comment by jimmyadaro** [comment]
I tried this: `@import "colors.scss";` and works like a charm. Doesn't create another "colors.css" nor "colors.min.css". May you close this issue?

- - -
**NodeJs:** v8.9.1
**sass-autocompile:** 0.13.3
