### ISSUE TITLE
Define main for all files in tree?

### ISSUE THREAD

**Issue by pr3cast** [armin-pfaeffle/sass-autocompile#133]
I've moved from Brackets to Atom today, and I want to import previous projects that use SCSS. Do I have to go in to each .SCSS file and define `//main:`, or is there a way to pre-define them so that I don't have to worry about it?

**Comment by armin-pfaeffle** [comment]
At the moment, the only possibility is to add the first-list-comment in each file. I'm sorry for that, but I'm planning to add a "watch"-feature.
