### ISSUE TITLE
sass autocompile for vs code

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [armin-pfaeffle/sass-autocompile#134]
hey there.
thanks for this awesome package. I wanted to know if you have any plan to make this as a vs code extension as well. I still couldn't find an extension working like sass-autocomplie.
it'll be really good to have this for vs code.

Regards

**Comment by armin-pfaeffle** [comment]
Hey! Yes, I think I will port my package to VS Code. The reason for that is, that I test this editor at the moment and it's makes fun to use it. My plan is to publish my extension at the beginning of 2018.

**Comment by liamjohnston** [comment]
I'm trying out VS Code now and this package is the main thing that's stopping me wanting to switch over. Can't wait! Great work on the package! :)
