### ISSUE TITLE
Output path not working

### ISSUE THREAD

**Issue by Kazuto** [armin-pfaeffle/sass-autocompile#135]
This is my folder structure how it should be.

```
/
├── index.html
├── css/
│   ├── stylesheet.css
└── scss/
│   ├── bulma/
│   ├── bulma.scss
│   ├── overrides.scss
│   ├── helpers.scss
│   └── stylesheet.scss
```

Input path: `./scss/`
SCSS catalog: `scss` 
Output path: `./css/`
CSS catalog: `../css/`

But it's getting compiled to the root directory and not the css folder.

**Comment by armin-pfaeffle** [comment]
In which file do you have placed the first-line-comment with the [`compile..,`](https://github.com/armin-pfaeffle/sass-autocompile#compilecompressed) paramter?

Here a working example for `stylesheet.scss` -- put this as first line:
```SCSS
// compileCompressed: ./../css/stylesheet.css

// Your SCSS comes here...
body {
}
```
