### ISSUE TITLE
Create another branch

### ISSUE THREAD

**Issue by reardestani** [armin-pfaeffle/sass-autocompile#14]
Hi,

Please create another branch so I can send pull request. 
The pull request is about enable four output styles as an dropdown so developer can choose their favorite style.

**Comment by armin-pfaeffle** [comment]
Hey!

Here you go [output-styles](https://github.com/armin-pfaeffle/sass-autocompile/tree/output-styles) ;)

**Comment by reardestani** [comment]
thanks, 

please create a dev branch so others can send pull requests better.
