### ISSUE TITLE
Problems with compiling when using CSS4 case-sensitivity selector

### ISSUE THREAD

**Issue by dperolio** [armin-pfaeffle/sass-autocompile#140]
So, I've been running into a problem in my project. I need to use case-sensitivity selectors, and they work fine with CSS, but sass-autocompile is throwing an error because of them and not allowing me to compile:

"Error: unterminated attribute selector for class" 

![bckgukp](https://user-images.githubusercontent.com/3791055/35085630-863159e4-fbf7-11e7-85a4-2569ae70914d.png)

I've checked with [https://www.sassmeister.com/](SassMeister) and it seems the problem is with LibSass, as everything else seems to compile without error.

This is a valid CSS code example that throws an error for reference:

.markup .text[class~="something" i]::before {
    content: 'Something';
}

Not sure there's anything you can do about this, or any way to bypass it, but it would be very helpful.

Thanks.

**Comment by armin-pfaeffle** [comment]
Hey! Because my package is only a wrapper for node-sass, I cannot help you here.

Send me an email (mail@armin-pfaeffle.de) with your problem and I will see what I can do for you.

**Comment by armin-pfaeffle** [comment]
Hey! Because my package is only a wrapper for node-sass, I cannot help you here.

Send me an email (mail@armin-pfaeffle.de) with your problem and I will see what I can do for you.
