### ISSUE TITLE
Error to install sass autocompile

### ISSUE THREAD

**Issue by stefanoconsole** [armin-pfaeffle/sass-autocompile#143]
When i install sass autocompile, he generate a infinite loop error.
![schermata 2018-03-19 alle 12 25 37](https://user-images.githubusercontent.com/32031262/37593038-ebdaaa04-2b70-11e8-8606-495a497cbdfe.png)

How to resolve it?

**Comment by armin-pfaeffle** [comment]
Hey! My package only uses node-sass, so I do not support such problems, sorry. Have a look at the [issue tracker](https://github.com/sass/node-sass/issues) of [node-sass](https://github.com/sass/node-sass). [Perhaps this helps](https://github.com/sass/node-sass/issues/2006)!?
