### ISSUE TITLE
Command Failed: node-sass --output-style compressed

### ISSUE THREAD

**Issue by vincentntang** [armin-pfaeffle/sass-autocompile#145]
![image](https://user-images.githubusercontent.com/10290348/38276064-d88e7456-3761-11e8-868d-95bd674090a9.png)

Getting this  error

Tried reinstalling the plugin on atom
Tried reinstalling nodeJS
Tried running `npm rebuild node-sass --force` per error report
Tried running `npm rebuild node-sass --force -g` to globally install

Still having this issue

- Version 8.11.1 `node -v`
- Version 5.6 `node-v`

**Comment by vincentntang** [comment]
It works now today some reason

- Reinstalled nodeJS with msi file https://nodejs.org/en/
- Restarted PC

I think that's all I did yesterday to resolve the issue

My avast antivirus and malware bytes have been giving me lots of problems in the past week, it could possibly be that as well

**Comment by armin-pfaeffle** [comment]
Hey!

Well, that looks like two different node.js versions were the problem. But I never had such an issue.

Perhaps the PATH variable was not updated correctly, so a restart may have fixed your problem.

Greats
