### ISSUE TITLE
Can I configure sass-autocompile to save to a different directory?

### ISSUE THREAD

**Issue by ghost** [armin-pfaeffle/sass-autocompile#147]
Right now I have it to convert to css on save but it is saving directly where my scss files are. Is there any way to save it like such? I didn't see a setting in the package preferences.

Main Directory
|
| - CSS - Folder where I want to keep my converted CSS
|
|- SCSS - Folder where I want to keep my original SCSS

**Comment by armin-pfaeffle** [comment]
Hey!

Yes, there is a way ;) I know, the documentation is really long, but it's good to read trough once! Have a look at the [parameters which can be defined in first-line-comment](https://github.com/armin-pfaeffle/sass-autocompile#parameters). Here any example:

Your SCSS file, e.g. `style.scss`:
```scss
// compileCompressed: ../css/$1.css

$main-color: red;
body { background: $main-color; }
```

If you save this file in your given SCSS folder, the output will be a compressed CSS file `style.css` in your CSS folder. `$1` is a placeholder for the filename which should be compiled, in this case `style`.
