### ISSUE TITLE
Question: Can I auto-upload compiled css to remote ftp?

### ISSUE THREAD

**Issue by hristov296** [armin-pfaeffle/sass-autocompile#149]
I am using the package remote-ftp which connects to my ftp server and allows me to save any changes directly to the ftp server. Can I make sass-autocompile to auto upload compiled css files to the server?

**Comment by armin-pfaeffle** [comment]
Hey! Such an feature is not implemented in my package, sorry!

Which OS do you use? On Windows you can use "map network drive" for adding a FTP folder nad then working with Atom on this directory. I nevery tried that, but it should word.
