### ISSUE TITLE
Error: argument `$color` of `darken($color, $amount)` must be a color\

### ISSUE THREAD

**Issue by dangthanhmiu** [armin-pfaeffle/sass-autocompile#151]
Hi!

I am switching to bootstrap 4, which is using sass and i got this error when saving the _variables.scss file.

`"line": 153,
  "column": 29,
  "message": "argument `$color` of `darken($color, $amount)` must be a color",
  "formatted": "Error: argument `$color` of `darken($color, $amount)` must be a color\n    `

These are the _variables.scss and style.scss source:

[style_variables.zip](https://github.com/armin-pfaeffle/sass-autocompile/files/2132827/style_variables.zip)

**Comment by armin-pfaeffle** [comment]
Can you please attache the file?

**Comment by dangthanhmiu** [comment]
Yes, I just attached it. Thanks

**Comment by armin-pfaeffle** [comment]
First of all, this is not a problem of my package because it's only a wrapper for node-sass. Beside that, it's a general SASS/SCSS problem and has nothing to do with node-sass.

Can you try to find the function `theme-color`? The file in which this function is defined must be imported before `_variables.scss`. Perhaps there is a `_functions.scss`?

**Comment by dangthanhmiu** [comment]
Thank you for your quick reply. If you have time, could you please test the newest bootstrap 4?. Properly there is a problem with it or if you can help to give a solution? I have been using only Less in bootstrap 3 all the time.

**Comment by armin-pfaeffle** [comment]
Compiling `bootstrap.scss` in `scss`subfolder of Bootstrap 4 works without any problem.

As I said, there is a `_functions.scss` in the Boostrap scss folder, which contains the `theme-color` function. The order of you imports is important!

**Comment by dangthanhmiu** [comment]
You are right, my bad to forget import the bootstrap.scss to style.scss file. Thank you for a great package. Problem solved now. :)
