### ISSUE TITLE
Any way to combine file header flags AKA parameters?

### ISSUE THREAD

**Issue by brndto** [armin-pfaeffle/sass-autocompile#153]
I want to achieve something like so:
`// main: site-*.scss, !compileOnSave`
I've tried the above and I've also tried this with no luck:
`// main: site-1.scss, site-2.scss (etc...)
// !compileOnSave`
and also tried this:
`// main: *.scss
// !compileOnSave`

Essentially, I have a SCSS source file for loading the styles for our blogs, the blogs use the same style with the only difference being the colours used across about 50 or 60 websites, I'd like to make sure the file with those params isn't getting compiled but at the same time, compile all the files which use that import (which only contains a mixin).

**Comment by armin-pfaeffle** [comment]
Hey!

Well, that's not supportet at the moment. But it's an interessting feature I can add in future.

If you don't add `compileOnSave` to the first-line-parameter, it's the same as your requested `!compileOnSave` which is not supported.
