### ISSUE TITLE
Compilation issue: Error @import

### ISSUE THREAD

**Issue by ann0812** [armin-pfaeffle/sass-autocompile#154]
Hello, 

I'm a programming-beginner, however, have a question regarding an error-warning in my atom-texteditor when trying to compile my .scss into an .css with sass-autocompiler, 

It appears when using the @import at the start of the .scss document; it says: media-query expression must begin with '('. However, when I add an '(' it's still not working but giving out an error-warning saying "invalid CSS".

Could somebody please help me with that issue? The solution is probably quite obvious for sb. experienced, but I just can't figure it out. 

Thanks in advance,
Ann
![screenshot 2018-07-19 14 41 21](https://user-images.githubusercontent.com/41433697/42942981-dda231e0-8b61-11e8-98d0-f005bc71a612.png)

**Comment by armin-pfaeffle** [comment]
Remove the brackets before and after `@import`.
