### ISSUE TITLE
Feature request: support for remote-ftp

### ISSUE THREAD

**Issue by Coding-Kiwi** [armin-pfaeffle/sass-autocompile#156]
Hi, great package!
Would it be possible to trigger a file-upload of the compiled file when compileOnSave is true?
I'm sure I'm not the only one using [remote-ftp](https://atom.io/packages/remote-ftp)

Keep up the good work

**Comment by artstylee** [comment]
yea im using it too
but it compiles only for local project and you have to upload the css by yourself
please support

**Comment by Coding-Kiwi** [comment]
Closing this old old issue.
Workaround would be using the .ftpconfig watch option which uploads changed files
