### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by ghost** [armin-pfaeffle/sass-autocompile#168]
I installed node-sass globally, but I'm still having trouble with this. I have Linux Mint, is this an issue?

**Comment by armin-pfaeffle** [comment]
Hey Ashley!

Well, if you have installed it globally, then you should be able to execute `node-sass` command via terminal. Let me see if I can help you tomorrow. Right now, I have no possibility to execute a VM.

**Comment by ghost** [comment]
> Hey Ashley!
> 
> Well, if you have installed it globally, then you should be able to execute `node-sass` command via terminal. Let me see if I can help you tomorrow. Right now, I have no possibility to execute a VM.

It's actually working now! I think I installed Atom using Software Manager a couple months back. I'm not 100% sure thats what I did, but I think so. I uninstalled it and reinstalled it through the terminal using the directions in the atom manual, because I couldn't use atom commands in the terminal either and was trying to see if reinstalling it a different way would help. I decided to also reinstall sass-autocompile in my new Atom installation and its working now. I'm not really sure why this is different though...

**Comment by armin-pfaeffle** [comment]
Great to hear! Have fun with this package ;)

**Comment by uvulpos** [comment]
Mh, I've got the same issue but reinstall seems not to work
![2020-09-03_01-12](https://user-images.githubusercontent.com/53957681/92046313-8d471a00-ed82-11ea-9a1d-ef06ab799c9e.png)

Because I could not install node-sass directly I installed it perm unsafe. But this should not make a difference

**Comment by uvulpos** [comment]
Interesting the command works in the terminal but not in the Atom plugin

![2020-09-03_01-20](https://user-images.githubusercontent.com/53957681/92046886-dba8e880-ed83-11ea-8b2b-798ff0b4825b.png)
