### ISSUE TITLE
Command failed : sass

### ISSUE THREAD

**Issue by welbinator** [armin-pfaeffle/sass-autocompile#170]
I installed the plugin, and turned it on by going to Packages > Atom SASS > compile file and it says it's watching for SASS.

THen when I save my style.scss file I get this error:

Command failed: sass "/home/jameswelbes/jwdigital/assets/scss/style.scss" "/home/jameswelbes/jwdigital/assets/scss/style.css"
/bin/sh: 1: sass: not found

Is this some kind of permissions issue?

**Comment by armin-pfaeffle** [comment]
Hey! Well, that's not my package you are talking about ;) My package does not add "Atom SASS" entry in main menu. Perhaps you are using [this package](https://atom.io/packages/atom-sass)?

**Comment by welbinator** [comment]
whoops! haha sorry =]
