### ISSUE TITLE
/bin/sh: node-sass: command not found

### ISSUE THREAD

**Issue by tommysvr** [armin-pfaeffle/sass-autocompile#175]
Hello,

I've seen a couple of other reports here and across the web but no fix has solved it for me yet.

I've installed nodejs and node-sass globally, but still get this issue. I even did a full erase and install of my Mac and tried again, but nothing.

Any ideas what I could try?

**Comment by pacollins** [comment]
@tommysvr - Did you figure out a solution? Having the same issue.

----

Found it:

For the future, you need to [reinstall `node-sass`](https://medium.com/@proustibat/how-to-fix-error-node-sass-does-not-yet-support-your-current-environment-os-x-64-bit-with-c1b3298e4af0)
