### ISSUE TITLE
No default settings for output file

### ISSUE THREAD

**Issue by junaidbhura** [armin-pfaeffle/sass-autocompile#18]
Hi first of all this is a great plugin. I think the following functionality would make this the best:

* Default options for output CSS file - maybe the same file name and directory as the source file?
* Right now when there is no output file specified, nothing happens. Instead, maybe it could work on the default option mentioned above?
* If the output file is specified in the SCSS file, then it works as usual

This way one does not need to add the output file in the code of the file. This is specific to the editor and plugin, rather than the CSS, so it shouldn't ideally be part of the code.

**Comment by armin-pfaeffle** [comment]
Hm, interessting idea! +1

I think I will add this feature with next version. I think in next two weeks I will publish it!

**Comment by michaeleahcim** [comment]
yea i agree i don't know how to code that much and i just installed atom and this plugin and i'm having problems because it doesn't compile straight to the root as a default so i'm trying to figure out how to do that

**Comment by PixelT** [comment]
+1 for default name and output this same as main scss file which is compiled

**Comment by armin-pfaeffle** [comment]
Please check the new version 0.10.0. I changed a lot of things there. Have a look, your requested features is supported now!

**Comment by junaidbhura** [comment]
This is brilliant! Works very well :)

**Comment by armin-pfaeffle** [comment]
Great to hear ;)
