### ISSUE TITLE
min.css file. Automatic save.

### ISSUE THREAD

**Issue by songminzy** [armin-pfaeffle/sass-autocompile#183]
hi

If I save the [test.scss] file,
[test.min.css] Can I save it automatically?
Should I press Save Star twice?

Is there an automatic save option here?

please

thank you

**Comment by armin-pfaeffle** [comment]
Hey. In general if you have installed my package and save a SCSS file, the file is compiled to CSS. Please check you settings. The option *Compile on Save* should be enabled:

![image](https://user-images.githubusercontent.com/531182/135054473-9e926a99-38fa-44b1-baec-c08435effc76.png)

If do do not want to have this option enabled, you can add a comment into your first line:

```
// compileOnSave

body { background: red }
```

> Should I press Save Star twice?

What do you mean with this?

**Comment by songminzy** [comment]
I modified the contents of the file, but the file [min.css] does not change. How can I solve this problem?

**Comment by armin-pfaeffle** [comment]
What is the value of the second Option *Compile files...*? It should be **Every SASS file**

Even if the **test.scss** is empty, it is compiled when I save the file:

![image](https://user-images.githubusercontent.com/531182/135056083-22008882-133f-4d8e-bac2-5ef6308d725f.png)

**Comment by songminzy** [comment]
[
![image](https://user-images.githubusercontent.com/58495804/135056772-cad9c717-b14b-46f5-9798-9c37fdcde8cd.png)
](url)


It's the same.

However, if i save [style2.scss],
There's a yellow warning at the bottom.

'no output style defined.....'

**Comment by armin-pfaeffle** [comment]
Have you read the warning? It tells you what you have to do.

**Comment by armin-pfaeffle** [comment]
Enable this option:

![image](https://user-images.githubusercontent.com/531182/135057630-202480dd-07ba-4271-9c38-04b54e112faa.png)

... or use an inline comment:

```
// compileCompressed

body { background: red }
```

Please read the documentation!

**Comment by songminzy** [comment]
![image](https://user-images.githubusercontent.com/58495804/135059503-163aea9c-30f1-455b-b847-322cb382a40e.png)


That problem still remains.

That yellow line is what I saved manually.

If I save style2.scss,
I want style2.min.css to be saved.

Is this impossible?

The same problem occurs even if you run it again after exiting the editor.

**Comment by armin-pfaeffle** [comment]
When you update the settings of my package, you must not restart the editor.

And that what you present is a totally different package. This has nothing to do with my package. My package is only for compiling SCSS to CSS.

**Comment by songminzy** [comment]
I understood. 
Thank you

**Comment by armin-pfaeffle** [comment]
Please read the documenation of every package in order to understand what's the purpose of every package and what it really does. It helps you a lot!
