### ISSUE TITLE
Specify an output directory when using multi-file compilation

### ISSUE THREAD

**Issue by rSafari** [armin-pfaeffle/sass-autocompile#19]
i get this error when ever i try to save a .scss file

Command failed: C:\Windows\system32\cmd.exe /s /c "node-sass --output-style compressed undefined/./css/sass//main.scss undefined/./css//main.css"
Specify an output directory when using multi-file compilation

i have only 1 file with the name of site.scss

and its like this

// out: site.css
body { 
    color: red;
 }

the file is been compiled and i get the main.css file, but this error make me crazy !
how can i solve this ?

**Comment by armin-pfaeffle** [comment]
Hey!

Please post your original first-line-comment please! Something is going wrong with the internal path building.

**Comment by rSafari** [comment]
this is all i have in my scss file ! 

// out: site.css
body { 
color: red;
}

**Comment by armin-pfaeffle** [comment]
Are you sure? The out parameters says that the filename is **site**.css and in the error message it's mentioned that it's **main**.css
```
undefined/./css/sass//main.scss
undefined/./css//main.css"
```
Do you save your file in a normal directory? Or is there any special about it? Network directory? FTP? WebDAV? I think sass-autocompile works with that, but haven't tested that yet.

**Comment by rSafari** [comment]
ok i found the problem and im sorry.
its not the problem with this package.
the problem was for sass-compiler package.
i removed that package and problem gone.

sorry for wasting your time ...

**Comment by armin-pfaeffle** [comment]
Ahhh, okay ;)

No Problem!
