### ISSUE TITLE
"Compile files" options (every file or only first-line comment) not working

### ISSUE THREAD

**Issue by soanvig** [armin-pfaeffle/sass-autocompile#23]
I have two files: *main.scss* and *_fonts.scss*. 
*main.scss* **has** first-line comment where I define output. Second line of the file is `@import 'fonts';`
*_fonts.scss* has only @font-face rules. No comments.
But everytime I save *_fonts.scss* it compiles.
I have "Compile files" options set to "Only with first-line-comment" in Package Settings tab.

Expected behaviour: file without first-line-comment should not compile.

**Comment by armin-pfaeffle** [comment]
Hey!

I fixed that bug with version 0.10.3. Now it should work!

Thanks for you report :)
