### ISSUE TITLE
Error while compiling, but it compiles!

### ISSUE THREAD

**Issue by arnekolja** [armin-pfaeffle/sass-autocompile#24]
Hi there,

I just set up a completely fresh Atom instance and installed sass-autocompile. For some weird reason, it is throwing a compile error, but compiles successfully.

The error is (take a look at 'undefined'):

    Command failed: /bin/sh -c node-sass --output-style compressed undefined/./scss//styles.scss undefined/.//styles.css
    /bin/sh: node-sass: command not found

The error comes as a popup message, but at the bottom the status output says it compiles successfully and the file is indeed successfully compiled.

The first line of my styles.scss looks like this:

    // out: ../css/styles.css, outputStyle: compressed

Any idea how to fix this?

**Comment by armin-pfaeffle** [comment]
Hey! That looks a lil bit crazy... The result of this:
```
// out: ../css/styles.css, outputStyle: compressed
```
normally could not be this:
```
undefined/.//styles.css
```
You use a Linux?

**Comment by arnekolja** [comment]
Uh, sorry, seems to be my fault. For some reason I have two sass compilers running. Yours works, but the other does not. Sorry, now that's embarrassing :-)

**Comment by armin-pfaeffle** [comment]
No problem :) Good to hear, that everyting works fine!

**Comment by mko** [comment]
Note: This issue still seems to happen when the user didn't have `node-sass` installed in `/bin/sh` and didn't manually set the path in Settings before attempting to compile the first time. The app then auto fixes the path in Settings, but the error persists on future compiles. The `apm rebuild-module-cache` fixes the issue. It might be worth putting the `apm rebuild-module-cache` in the FAQ for the package.
