### ISSUE TITLE
Update and now Command failed, why?

### ISSUE THREAD

**Issue by Amstramgram** [armin-pfaeffle/sass-autocompile#25]
Hello,

i update with the latest version and now i have this error:
Command failed: /bin/sh -c node-sass --output-style compressed --indent-type space --indent-width 2 --precision 5 "path_of_my_sass_file" "path_of_my_css_file" /bin/sh: node-sass: command not found.

i don't know why, it's works fine before that.

In my main.sass file i have on first line : // compileCompressed: main.css

echo $PATH: /Users/myname/.rvm/gems/ruby-2.2.2/bin:/Users/myname/.rvm/gems/ruby-2.2.2@global/bin:/Users/myname/.rvm/rubies/ruby-2.2.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/opt/ImageMagick/bin:/Users/myname/.rvm/bin
Mac OSX:  v Yosemite 10.10.5
Atom: v 1.0.19
sass-autocompile: v 0.10.3

What i doing now ?

Thank you, 
awesome package

**Comment by armin-pfaeffle** [comment]
Hey!

There was an error in the versions before. First you can try to enter the following command to terminal, restart atom and retry to compile. But I don't think that this will fix your problem.
```
apm rebuild-module-cache
```
It's interessting that the `node-sass` command is not available for Atom, but I think it has to do with an permisson issue, [decribed here](https://github.com/armin-pfaeffle/sass-autocompile/issues/4#issuecomment-141167117). What is the output when you enter `node-sass` in terminal? Try to find out where the `node-sass` command is places (→ `which node-sass`) and set the path, where command is placed, to option [Path to 'node-sass' command](https://github.com/armin-pfaeffle/sass-autocompile#path-to-node-sass-command). Does this help you?

**Comment by Amstramgram** [comment]
Ok i am fucking idiot. I put the path for node-sass on first line and not in setting panel. I am sorry.
Thank you for reply so fast !

**Comment by armin-pfaeffle** [comment]
Great to hear that everything works now ;)

**Comment by juliancoleman** [comment]
`apm rebuild-module-cache` worked for me.
