### ISSUE TITLE
node-sass

### ISSUE THREAD

**Issue by Mobilpadde** [armin-pfaeffle/sass-autocompile#27]
For some reason atom can't reach node-sass?

I'm using Mac OS X El Capitan (10.11), with node-sass installed globally ([1] & [2]), but getting an error in atom ([3]).

[1]: http://puu.sh/kLB7q/a56b535671.png
[2]: http://puu.sh/kLBlW/40738cc603.png
[3]: http://puu.sh/kLBhj/3446089ed5.png

**Comment by heatwaveo8** [comment]
Same problem here. Latest Atom version on El Capitan. Installed globally and am getting the following: 
/bin/sh: node-sass: command not found

**Comment by armin-pfaeffle** [comment]
Hey! Great to hear that it works for you, heatwaveo8.

What about you Mobilpadde? Could you fix your problem by setting **Path to `node-sass` command** option? ([see documentation](https://github.com/armin-pfaeffle/sass-autocompile#path-to-node-sass-command))

**Comment by Mobilpadde** [comment]
Hmm, yea, that works! Thanks!
