### ISSUE TITLE
wrong file opened after click on error

### ISSUE THREAD

**Issue by yoorek** [armin-pfaeffle/sass-autocompile#28]
When error is detected and displayed in bottom panel clicking on the file name with error gets me to the main file not the file with error.

app.scss:

`@import 'button'
...`

button.css :
`
 //main: app.scss `

when error is detected in button.scss clicking on error gets me to app.scss

**Comment by armin-pfaeffle** [comment]
Thanks for your report! I fixed this bug with version 0.10.5 which I release right now!

**Comment by yoorek** [comment]
updated to 0.10.5 and still has the same error behavior

**Comment by armin-pfaeffle** [comment]
Can you give me some test content? With latest version, everything seems to work now.

**Comment by yoorek** [comment]
Just like I wrote before. I just checked with simple test files:

main.scss:

@import 'child';


child.css:

// main: main.scss

bad: {

**Comment by armin-pfaeffle** [comment]
Do you mean child.**scss** or child.**css**?? What is the error message? Can you post a screenshot?

**Comment by yoorek** [comment]
It does not matter what is the error message - make any error in child file (in my case I did not close bracket) and click on it - main file is opened.

<img width="654" alt="zrzut ekranu 2015-10-16 o 10 45 08" src="https://cloud.githubusercontent.com/assets/271500/10537583/08777fda-73f3-11e5-9ee1-1d491c029238.png">

**Comment by armin-pfaeffle** [comment]
Well, the only thing i can imagine is that Atom caches the old version because here it's working as it should. Can you have a look at this file:
```
/Users/<username>/.atom/packages/sass-autocompile/lib/sass-autocompile-view.coffee
```
... and post content of line **171**. It should look like this:
```
@addText(errorMessage, 'alert', 'error', (evt) => @openFile(args.message.file, args.message.line, args.message.column, evt.target))
```

After that, you can try executing the follwing command in your terminal and restart Atom:
```
apm rebuild-module-cache
```

**Comment by yoorek** [comment]
the 171 looked like it should.

cache rebuild helped! wonder if it's Atom fault and I should rebuild cache manually after every plugin update ? quite annoying if it's the case.

Anyway, thanks for help!

**Comment by armin-pfaeffle** [comment]
It seems that this my fault and not Atoms. There must be any binding which I do not dispose or something like that. I must have a closer look at my code.
