### ISSUE TITLE
I can't compile scss file but run it sucess if copy command into the terminal!

### ISSUE THREAD

**Issue by pacez** [armin-pfaeffle/sass-autocompile#32]
I can't compile scss file but run it sucess if copy command into the terminal!

The atom panle output:  "cmmonad faild: /bin/sh/ -c /usr/local/lib/node_modules/node-sass/bin/node-sass --output-style compressed --indent-type tab --index-width 2 --precision 5 "/Users/pacez/Documents/study/express/pana/public/stylesheets/style.scss" "/Users/pacez/Documents/study/express/pana/public/stylesheets/style.css" env:node: No such file or directory "

But   "cd  /usr/local/lib/node_modules/node-sass/bin/ "   and run "node node-sass --output-style compressed --indent-type tab --index-width 2 --precision 5 "/Users/pacez/Documents/study/express/pana/public/stylesheets/style.scss" "/Users/pacez/Documents/study/express/pana/public/stylesheets/style.css"  is compile success!

The screenshot as follow:
![atom panel](https://github.com/pacez/pacez.github.io/blob/master/doc/atom_panel.png?raw=true)
![terminal](https://github.com/pacez/pacez.github.io/blob/master/doc/terminal.png?raw=true)

**Comment by armin-pfaeffle** [comment]
Have to installed **node-sass** globally?
```
npm install node-sass -g
```

My packages uses the command `node-sass` and **not** `node node-sass`. What happens if you open terminal and execute the command `node-sass`?

You can try to find out where `node-sass` is placed, via `which node-sass` and set the path to the executable to option **Path to 'node-sass' command**. When you have installed it globally, the path should be `/usr/local/bin`.

**Comment by slidese** [comment]
I have the same problem (installed node-sass globally). The `which node-sass` command gives me `/usr/local/bin/node-sass`. Tried restarting Atom but still the same error.

I then manually set the **Path to** as you described above and then got it working.

**Comment by armin-pfaeffle** [comment]
The problem why this error occurs is that there are different permissions for Atom when starting from terminal or from Dock. I don't know why this is the case, but that's why you have to set that option.

Perhaps I have to think about automatic adding this path to options.

**Comment by pacez** [comment]
Thanks for you reply, Look forward to your update!

**Comment by pacez** [comment]
@armin-pfaeffle, Thanks for you reply, Look forward to your update!

**Comment by armin-pfaeffle** [comment]
I released version 0.11.0 two days ago. It has a new, "hidden" feature that searches for node-sass command in known directories when an error occurs while compiling. So, if node-sass command can not be found, but directory can be fixed by sass-autocompile, user is asked for applying that fix.

**Comment by Senia-Burrell** [comment]
I get this error when i save a scss file in Atom
"/bin/sh: line 1: /node-sass: No such file or directory"

I have tried putting the path to node-sass, reinstalling node-sass. Nothing works

**Comment by armin-pfaeffle** [comment]
Did it work then for you?

**Comment by Senia-Burrell** [comment]
Yes it did



[image: Inline image 1] <http://www.medullan.com> *Senia Burrell*
*Associate, Technology*
Medullan Inc. | medullan.com <http://www.medullan.com>
t: +1 617 547 0273
e: sburrell@medullan.com
