### ISSUE TITLE
Doesn't compile to file.

### ISSUE THREAD

**Issue by vladcraft** [armin-pfaeffle/sass-autocompile#33]
Install all needs to compile sass/scss to css. Try compile to file, nothing happened. Try direct compile and file compiled and replace source code sass, as it should be. 
Why doesn't works compile to file, but direct compile works without problems.

atom 1.1.0
sass-autocompile 0.10.7

**Comment by armin-pfaeffle** [comment]
Hey!

How do you try to compile file? Do you want to compile on save? Do you have correct file extension (`.sass` or `.scss`)?
 Please check options [Compile on Save](https://github.com/armin-pfaeffle/sass-autocompile#compile-on-save) and [Compile files ...](https://github.com/armin-pfaeffle/sass-autocompile#compile-files-) too!

Did this help you?

**Comment by vladcraft** [comment]
I try  compile scss sass file with "compile on save", try manual compile with shortcut key and try with packeges-->...-->compile to file.

Reinstall atom and plugin. issue clozed. all work. Ty for fast  answer

**Comment by armin-pfaeffle** [comment]
Great to hear that it works now!
