### ISSUE TITLE
How to compile Compass?

### ISSUE THREAD

**Issue by ashramwen** [armin-pfaeffle/sass-autocompile#35]
I uses Compass in my project.
When I build .scss file, there is an error.
**Error: file to import not found or unreadable: compass/css3**
How should I solve this problem?

BTW I can compile .scss with compass in sublime text 3.
I don't what's wrong
My OS is mac os.

**Comment by armin-pfaeffle** [comment]
Can you post a minimal example of your usage of compass so I can test your problem?
