### ISSUE TITLE
Change path for css auto generated

### ISSUE THREAD

**Issue by ialex90** [armin-pfaeffle/sass-autocompile#36]
It works, like this ../css/$1.min.css
Sorry!

**Comment by armin-pfaeffle** [comment]
Do you think that this is not clear enough in documenation?

**Comment by ialex90** [comment]
I already fixed, for this reason I auto-closed the issue, So I can not delete it.

**Comment by armin-pfaeffle** [comment]
Issues should not be deleted! They can help others to solve their problems.

Have you read my question?

**Comment by ialex90** [comment]
Yes I did it, for me it was not enough clear, even I tried to set up the file and I put something like this:

      ./../css/fileName.ext

not sure exactly the same but I got an error and I tried to fix it unsuccessful. Then, I tried another plugin like where the path is much clear to set up but it was not working on MAC, only for Win. I came back and I solved it!
