### ISSUE TITLE
Compiling partials

### ISSUE THREAD

**Issue by jbaf** [armin-pfaeffle/sass-autocompile#37]
Hello, and thanks for this plugin.
It works fine when compiling a normal scss file. My problem is with the partials ( _myfile.scss )... It seems that It can't find variables and mixins stored in other partials that the one I'm trying to compile.

It keeps telling me "ERROR: Undefined variable: "$myvariable" " (same for mixin), when I save and compile from a partial file.
When I do it from command line with node-sass, it works fine though...

FYI, my project tree is structured like this : 
/
l
l -- /scss
     l 
     | -- main.scss
     l
     l -- /components
          l
          l-- _partial.scss
l
l -- /css

Am I doing something wrong ?
Thanks !

**Comment by armin-pfaeffle** [comment]
Hey!

Have you defined a [`main` parameter](https://github.com/armin-pfaeffle/sass-autocompile#main) in your partial files? If so, the panel or notification message should ouput that `main.scss` is compiled.

Here reduced example:
```
/
| -- main.scss
| -- _options.scss
| -- /partial/_test.scss
```

`main.scss`
```sass
/* compileCompressed: css/$1.min.css */

@import "options";
@import "partial/test";

body {
    background-color: $body-background-color;
    @include set-font-color();
}
```

`_options.scss`
```sass
/* main: main.scss*/

$body-background-color: black;
$default-font-color: red;
```

`partial/_test.scss`
```sass
/* main: ../main.scss */

@mixin set-font-color() {
    color: $default-font-color;
}
```

The `main` parameter in `_options.scss` and `partial/_test.scss` ensures that saving these two files, leads to a compilation of `main.scss` and **not** one of the two partial files. In the `main.scss` the first thing I do, is to import the partial files, so every code is known after that. This is how it should work.

Does this help you?

**Comment by jbaf** [comment]
Thanks, It works fine that way.
That beeing said, it means that I have to go in every partial of my project and add the comment to the first line... It's not very convenient.
And the compiled file is written in the same folder that the scss file, instead of compiling in css folder. Is there a way to specify the output folder.

I may bea big noob, but I cant' find the way to do it.

Thanks again.

**Comment by armin-pfaeffle** [comment]
If you want to use `Compile on Save` feature you have to add the `main` parameter to every partial file at the moment. Only then the main SASS file is compiled on every change.

Yep, you are right that it's not the best way. But you can disable the `Compile on Save` feature and compile the main file via the Tree View context menu (→ Compile SASS) or you open the main file and use shortcut `ctrl-shift-c` for starting compilation of opened SASS file.

When you have any idea, how to improve that beahiour without creating a kind of configuration file, please let me know!

In order to write the ouput to a subdirectory or an absolute path you can setup the [corresponding parameters](https://github.com/armin-pfaeffle/sass-autocompile#compilecompressed). An example:

```sass
/* compileCompressed, compressedFilenamePattern: "../css/minified/$1.min.css" */
/* This paramters tells node-sass to output the CSS files to this relative path ../css/minified/
   If SASS file is named 'Foo.sass', the resultant filename is Foo.min.css */
```

You can use the short form too:
```sass
/* compileCompressed: "../css/minified/$1.min.css" */
```

...or you even can define multiple outputs:
```sass
/* compileCompressed: "../css/minified/$1.min.css", compileExpanded: "../css/$1.css" */
```

**Comment by jbaf** [comment]
Thank you for these precisions. That's nice of you to take the time to answer.
I guess I'll work that way, and see if it suits me.
Thank you again.

**Comment by armin-pfaeffle** [comment]
No problem! Great that it works now und it's clear how my package works.

If you have any improvement, let me know!

**Comment by geometron** [comment]
Is it possible to have more than one main? My project has a standard main.scss with partials and also a ckeditor.scss that only includes some of the partials for the CMS' editor. I tried 
`/* main: main.scss, ckeditor.scss */`
but only the first one is output and 
`/* main: main.scss, main: ckeditor.scss */` 
but only the second one is output

**Comment by armin-pfaeffle** [comment]
At the moment it's not possible, sorry! But I will include this features.

**Comment by nahuelhds** [comment]
The multiple main files would be an excellent addition

`/* main: main.scss, ckeditor.scss */`

Very helpful!
