### ISSUE TITLE
I can't compile scss file, Terminal output "No such file or directory"

### ISSUE THREAD

**Issue by pacez** [armin-pfaeffle/sass-autocompile#38]
Hi guys,  Terminal output "No such file or directory". But  the file is already existing。
The screenshot as follow:
![t1](https://github.com/pacez/pacez.github.io/blob/master/doc/t1.png?raw=true)
![t2](https://github.com/pacez/pacez.github.io/blob/master/doc/t2.png?raw=true)

Hope you reply

**Comment by armin-pfaeffle** [comment]
Hey! I think it has to do with your node or node-sass installation. Have you installed node-sass globally? Can you try to uninstall and reinstall node-sass again?

```
npm uninstall node-sass -g
npm install node-sass -g
```

After that you should clear the option `[Path to node-sass command](https://github.com/armin-pfaeffle/sass-autocompile#path-to-node-sass-command)` in Atom and try to compile a SASS file. I node-sass cannot be found, my packages supports you a fix!

**Comment by pacez** [comment]
Thanks for you reply! I have set  the option [Path to node-sass command] is "/usr/local/bin"  , The issue has fixed.
