### ISSUE TITLE
Selecting an output path for the .css file.

### ISSUE THREAD

**Issue by iamtirado** [armin-pfaeffle/sass-autocompile#39]
I cannot find how to choose the output path of the css. So far I must place the scss file in the location I want the css file to be compiled to. I would be great if I could have my app.scss in a scss folder and choose to outputh the app.css to ../css/ from my scss folder.

**Comment by armin-pfaeffle** [comment]
Hey!

You can use the [pattern parameters](https://github.com/armin-pfaeffle/sass-autocompile#compressedfilenamepattern) to write output to a different path, e.g.

```
// compileCompressed: ../css/minified/test.css
```

I will update documenation soon!

**Comment by iamtirado** [comment]
oh sweet. Thanks.
