### ISSUE TITLE
No support for multiple include paths

### ISSUE THREAD

**Issue by drod66** [armin-pfaeffle/sass-autocompile#41]
The auto compile fails with multiple include paths.
e.g. I have two include paths:
```
// compileExpanded: ../public/css/my.css, includePath: [../common_sass, ../node_modules/bootstrap-sass/assets/stylesheets]
@import "mysharedsass"; // found in common_sass
@import "bootstrap/normalize"; // found in bootstrap module
```

**Comment by armin-pfaeffle** [comment]
Yes, you are right... At the moment, there is no possibility to setup arrays. But I will have a look at this today, if there is another possiblity to allow multiple paths!

**Comment by armin-pfaeffle** [comment]
I have written a patch for node-sass. I hope it will be applied soon, so you can use multiple include paths.

**Comment by armin-pfaeffle** [comment]
Hey! There is no necessary change for node-sass. So update sass-autocompile to at least 0.12.1 and you can use multiple include paths.

**Comment by drod66** [comment]
Works perfectly! Thank you!
I noticed that node-sass defines "includePaths" instead of "includePath". Maybe sass-autocompile should align with it (or support both). Again, thanks for your quick fix! Really appreciated.

**Comment by armin-pfaeffle** [comment]
> I noticed that node-sass defines "includePaths" instead of "includePath". Maybe
> sass-autocompile should align with it (or support both).

What exactly do you mean with that? Supporting both? My package supports both ;)

But I have seen that in options there is a wrong description.
