### ISSUE TITLE
Error while compiling: node-sass command not found

### ISSUE THREAD

**Issue by hafezoa** [armin-pfaeffle/sass-autocompile#42]
Hello,

It is compiling properly but the error messages are still appearing.
<img width="1280" alt="screen shot 2015-12-14 at 4 54 08 pm" src="https://cloud.githubusercontent.com/assets/8918362/11795263/cb2e6fca-a283-11e5-9e21-4682bdd6970a.png">
<img width="1280" alt="screen shot 2015-12-14 at 4 56 45 pm" src="https://cloud.githubusercontent.com/assets/8918362/11795264/cb30d7b0-a283-11e5-84b2-d0417bef841c.png">
<img width="1280" alt="screen shot 2015-12-14 at 4 57 29 pm" src="https://cloud.githubusercontent.com/assets/8918362/11795265/cb35867a-a283-11e5-9517-814aa3977c8d.png">

**Comment by armin-pfaeffle** [comment]
Hey!

When this error message occurs, my package does not compile any SASS file. Do you use any other SASS compiler in Atom?

To fix that problem, you should have a look at the option [Path to node-sass command](https://github.com/armin-pfaeffle/sass-autocompile#path-to-node-sass-command). It's the last the option on the options page. Set it to `/usr/local/bin` and then it should work.

But with latest version, Atom should ask you for fixing that problem automatically. Which version of sass-autocompile do you use?

**Comment by hafezoa** [comment]
Hey Armin,
 
I am definitely using the latest version of Atom. I even got the prompt you are talking about that automatically populates the field and even tried debugging the issue by searching online. The solution that keeps coming up is the one you just mentioned but it did not no good.
 
In short, the issue is occurring with our without this fix.
 
Regards,
Omar

**Comment by armin-pfaeffle** [comment]
I meant the latest version of my package ;)

Are you sure you only use my package for compiling SASS? Because I don't think that my package compiles your SASS file and throws this error message.

Another hint is the "undefined" part in the error message, I overlooked until now. Can you post your options here? Something seems to be really strange here...

Have you tried to uninstall and reinstall my package?

**Comment by hafezoa** [comment]
Hey Armin,

Yeah you are absolutely correct. I had another complier called “sass-autocompile” [see screenshot]. After disabling it (and then uninstalling), the error no longer appears.



Really sorry for wasting your time! Do I need to do anything to close out the bug? This is embarrassingly my first time actually opening a ticket.

Omar

**Comment by armin-pfaeffle** [comment]
Hey! No problem! Great to hear, that everything works now as expected.

You can close this ticket when you login to GitHub and open this issue. I will close it so you do no have to do that.
