### ISSUE TITLE
Built-in imports

### ISSUE THREAD

**Issue by jerone** [armin-pfaeffle/sass-autocompile#44]
It doesn't seems possible to use the built-in imports. E.g. `@import "compass/css3/box-sizing";` will throw an error.

**Comment by armin-pfaeffle** [comment]
As far as I know, this is a compass/node-sass problem and not a problem of my packages. [Here](https://github.com/sass/node-sass/issues/54) you find a answer for that issue.

**Comment by jerone** [comment]
Thanks for the information. I was in the understanding that Compass was part of Sass. So there's no way to use Compass, not something like `npm install node-compass`?

**Comment by armin-pfaeffle** [comment]
Well, it won't be that easy, I think. I never used Compass, so I only can speculate. Have a look at [this issue](https://github.com/fourseven/meteor-scss/issues/3), especially at the end. Perhaps it helps you.

At the moment, I do no have to the time, to work through Compass an the extensions. Sorry!

But I let this issue opened, so I will have a look at it, next year!

**Comment by smnbbrv** [comment]
I actually solve the compass issue by this great thing: https://github.com/Igosuki/compass-mixins.

Unfortunately the author does not seem to support it anymore, but at least you have something you can use. I just forked it for my needs and add there the things I take from original compass library.

In short, just install this compass-mixins thing with bower or npm and then include it with include paths option of atom-sass-autocompile, you'll have there something like `/full/absolute/path/to/your/project/node_modules/compass-mixins/lib`. This works like charm for me.

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
