### ISSUE TITLE
Compiling not partials 

### ISSUE THREAD

**Issue by rocchidavide** [armin-pfaeffle/sass-autocompile#45]
What can I do if I have partials imported in a main.scss file and I want to compile only main.scss?

**Comment by brendanarnold** [comment]
I have similar problem - I edit a partial and save, it runs a compile but the main.scss that imports the partial is not compiled. I have to save the partial then switch to main.scss and 'Save' that to trigger a compile of main.scss including the changes on the partial.

**Comment by hultberg** [comment]
Duplicate of #37 

You must define the main file in the top of each partial:
`main.scss`
````
/* compileCompressed: css/$1.min.css */

@import "_partial";
````

`_partial.scss`
````
/* main: main.scss*/

.my-rule {
  color: #ffffff;
}
````

**Comment by armin-pfaeffle** [comment]
Thanks hultberg ;)
