### ISSUE TITLE
Status Bar Notification Type

### ISSUE THREAD

**Issue by jerone** [armin-pfaeffle/sass-autocompile#46]
I want to propose a third [notification type](https://github.com/armin-pfaeffle/sass-autocompile#notification-type); a tile in the [status-bar](https://github.com/atom/status-bar). 

I saw this at the [jade-autocompile](https://github.com/ManRueda/jade-autocompile/blob/f8d59e93f157333a24df0994d90412a0ae41cd5b/lib/jade-autocompile-view.js#L46) package, it's less obstructive then a popup/notification or panel while still containing the basic information if a file is compiled.

**Comment by armin-pfaeffle** [comment]
Good idea! I think, I will add this feature!

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
