### ISSUE TITLE
cannot find the settings / options panel/area for this plugin

### ISSUE THREAD

**Issue by propertunist** [armin-pfaeffle/sass-autocompile#48]
thanks for this code! 
i am a new atom user and looking to use this plugin for my scss files. i have installed this plugin and also node-sass via the terminal in fedora.. however, i am seeing an error message when i save an scss file that refers to the node-sass command not being found.
i saw a comment here that says to check the path for node-sass in the options/settings area for the plugin, but i am not able to find this page.. when i click on the Sass-autocompile submenu in the 'packages' menu in atom, there is no option there to view a full list of other options.
any idea what i am missing here?

**Comment by armin-pfaeffle** [comment]
Hey!

There are two ways to option Settings view: 
1. In main menu click on `Packages -> Settings View -> Open`
2. The better way is to press `Ctrl+,` (`Ctrl+Comma`).

On the left you can find the item `Packages` and there you can search for `sass-autocompile`. My plugin appears where you can click on the `Settings` button. And on this page you should have a look at `Path to node-sass command`.

![screenshot-a](https://cloud.githubusercontent.com/assets/531182/12675108/45c815a6-c688-11e5-8747-9598f9920d66.jpg)

![screenshot-b](https://cloud.githubusercontent.com/assets/531182/12675113/4ba9297e-c688-11e5-8478-3213db7fbc39.jpg)

**Comment by propertunist** [comment]
right, ok - yes that is where i was already looking. for some reason there is no settings button for your plugin in my version of atom. i am running the latest version of atom on fedora 23 (64 bit) and also version 0.12.2 of your plugin.

**Comment by armin-pfaeffle** [comment]
Hm... That's a lil bit strange. Restarted Atom already? Removed und installed my plugin again?

**Comment by propertunist** [comment]
ah, so after restarting atom i can see the settings panel and have now correctly entered the path for node-sass and got the plugin working. thanks for the tip :)

**Comment by armin-pfaeffle** [comment]
Hm, it seems that Atom has a bug here. Good to hear that it works now :)
