### ISSUE TITLE
Regex to exclude partial file compilation

### ISSUE THREAD

**Issue by wguldin** [armin-pfaeffle/sass-autocompile#49]
Hi, 

Just trying out Atom for the first time, and found your useful plugin. I know others have mentioned this, but using comments for partials is kind of burdensome. 

You mentioned you were open to other approaches. The sublime save on build package allows a user regex string that it then tests file names against to determine if they should be excluded. 

My standard, and I think it's pretty common, is to prefix partial files with an underscore, like `_partial.scss`. The following regex would cover that: `/^_.*\.scss/g`.

So, allowing a custom regex filter would probably solve this for a lot of people. It seems like a better solution, but I know nothing about developing for atom. If it's not possible, or not popular, that's fine too!

**Comment by armin-pfaeffle** [comment]
Hey! Have a look at [this issue](https://github.com/armin-pfaeffle/sass-autocompile/issues/52). I think, it's the same problem, but I must say, that your idea is smarter than my current solution!

I will let this request opened and I will see how to include this feature!

**Comment by wguldin** [comment]
Thanks for looking into this! 

It is the same issue, and I think taking underscores into account would be fine, a regex for it is probably overkill. 

According to the sass documentation, that's the way you're supposed to do declare partials, so it'd work pretty well for this tool: 

http://sass-lang.com/guide#topic-4

**Comment by armin-pfaeffle** [comment]
In regard to Partials, you are right. But your idea is great, if there is a need for more features which are based on filenames. At the moment, there is no reason to integrate it, but who knows what's coming next ;)

**Comment by wguldin** [comment]
Yeah, that's a great point, a custom regex would be super flexible. I think the sublime plugin did that because it supported 'save on build' for any build you were doing. To make it easier, you could have two options. A checkbox for the traditional partial, and then a second field allowing a custom regex.
