### ISSUE TITLE
What am i doing wrong?

### ISSUE THREAD

**Issue by foodgy** [armin-pfaeffle/sass-autocompile#50]
Hello. I'm new to sass :| 

Currently i'm trying to compile Foundation framework [scss files](https://github.com/zurb/foundation-sites/tree/develop/scss) with your sass-autocompile for Atom. Don't know why, but ```foundation.scss``` always compiles into empty ```foundation.css```.

What am i doing wrong?

```node.js``` & ```node-sass``` are both installed (globaly)
foundation [scss](https://github.com/zurb/foundation-sites/tree/develop/scss) files

**Comment by armin-pfaeffle** [comment]
No, you are not doing anything wrong. I had a quick look at Foundation framework and -- the name tells us ;) -- it's only a framework. This framework is a collection of mixins and functions, which are not used in any file, so there cannot be any output. It's up to you to write SASS "code" which use these.

I added the following "code" at the end of `foundation.scss` which uses the `foreground` function defined in `util/_color.scss` -- it was only a test, please do not add anything to this file ;)
```
body {
    color: foreground(red);
}
```

After I compiled the `foundation.scss`file, the content of the minified file was:
```
body{color:#fefefe}
```
