### ISSUE TITLE
@import error

### ISSUE THREAD

**Issue by kthornbloom** [armin-pfaeffle/sass-autocompile#51]
Hello, thank you for this plugin! I ran into an error, and wondered if you could help clarify what to do. I have two files, stylesheet.scss and test.scss, both in the same css folder. 

Within stylesheet.scss, I am importing the other like this:

`@import test;`

but I receive an error: **@import directive requires a url or quoted path**. What do I need to do, considering they are both in the same folder? I tried using the plugin settings and added "/css" under Include Paths, but it didn't help.

**Comment by armin-pfaeffle** [comment]
Hey! Well, you already have read the solution ;) **... quoted path ...**
```
// WRONG:
@import test;

// RIGHT:
@import "test";
```
