### ISSUE TITLE
Change how compile of partials work

### ISSUE THREAD

**Issue by hultberg** [armin-pfaeffle/sass-autocompile#52]
Hello,

I see that this package compiles partial files if it does not have the main file refrenced in the top of each partial. How about detecting this on each file if it has underscore as the first character on the filename?

My setup only has one single main file in the root of my sass folder and each partial is located in sub-directories. Maybe the package could have a main file defined somewhere and then... do the magic?

Hope you understand. I could try too cook a PR on what I mean.

**Comment by armin-pfaeffle** [comment]
Thanks! Fixed with 0.12.3.
