### ISSUE TITLE
Can't find a way to set up options...

### ISSUE THREAD

**Issue by smnbbrv** [armin-pfaeffle/sass-autocompile#54]
Hello, I really can't find how to set up the options...

![image](https://cloud.githubusercontent.com/assets/13453858/13432616/b9644a20-dfce-11e5-9358-c53f82b3952c.png)

Am I doing something wrong? Usually the Options button should be rendered on the left side of Uninstall button...

Should I set them in some configuration file?

**Comment by armin-pfaeffle** [comment]
Hey! Have you tried restarting Atom? In some cases I had same problem with other plugins and this helped me.

**Comment by smnbbrv** [comment]
oh, boy, that was it. Thank you, @armin-pfaeffle !
