### ISSUE TITLE
Blocker error when main file is not existing

### ISSUE THREAD

**Issue by smnbbrv** [armin-pfaeffle/sass-autocompile#55]
Hello again, actually a great tool!

What I found out so far, when you specify a not existing main file (that happened to me at first) there is an unhandled exception shown and after that the package does not work until you restart Atom. In fact if you make a mistake, you need to restart Atom.

Is there any way to fix that?

**Comment by armin-pfaeffle** [comment]
Have a look at [issue 58](https://github.com/armin-pfaeffle/sass-autocompile/issues/58). I think it's the same bug! I fixed it with version 0.12.4.
