### ISSUE TITLE
Include paths not seem to be working

### ISSUE THREAD

**Issue by ferarguelles** [armin-pfaeffle/sass-autocompile#57]
First of all, great package! Thanks for keeping it up!

On 0.12.3 the input paths for selecting main.scss files with @import declarations seem not to work. I enter the path surrounded by quotes, and yet it won't compile when saving partials.

**Comment by armin-pfaeffle** [comment]
Hey! Do you have a simple example?

**Comment by ferarguelles** [comment]
Sure. As you can see on the screenshot, I have a main.css file full with @import declarations. 

<img width="1073" alt="screen shot 2016-03-04 at 16 09 46" src="https://cloud.githubusercontent.com/assets/456452/13530964/40fabf9e-e224-11e5-881b-4374ebda0416.png">

On the right side of the image, is the package settings page for your package. I enter the path to the directory containing my main.css, with the imports.

If I change something in the partials, the main.css doesn't get considered in the compiling process.

**Comment by armin-pfaeffle** [comment]
Sorry for my late answer. I really have to do a lot at the moment.

On my Windows machine, everything seems to works fine. Here my configutation:

1. Set "Include Path" option to `'D:\tmp\test'`
2. Defined a test file `ttttt.scss`
3. Added import-declaration in any SCSS/SASS file: `@import "ttttt";`
4. ... and it worked.

Have you tried to use double quotes? Perhaps MacOS or Linux does not work with single quotes?

**Comment by goronfreeman** [comment]
I can confirm it's not working on OS X, even using double quotes. When I alter one of the partials that is imported into my main.scss file, main.scss does not compile. I need to switch over to my main.scss file and save it before any styles will update.

**Comment by armin-pfaeffle** [comment]
I think I missunterstood the main question...

My package should work like that! The include path is for defining the location of a SASS framework or your collection of general styles. These framework/styles do not know anything about your specific projects and should not. So it must not recompile the project specific styles.

**Comment by goronfreeman** [comment]
Oh, that makes sense then! I didn't quite understand the purpose from the README description. It would be great to be able to get the main SCSS file to re-compile after one of the imported stylesheets is updated. Should I open an issue for a feature request?

**Comment by armin-pfaeffle** [comment]
Well, I don't think so. If you have about 20 projects that reference your SASS framework, do you really want to recompile every 20 project styles? Do you know about all consequences at that moment? I think that it's better that the developer has to recompile on his own, so he really knows what is compiled.

**Comment by goronfreeman** [comment]
Sorry, I wasn't clear enough with what I was asking. It would be another option available on a project by project basis, not for a SASS framework or shared global styles used in multiple projects. For example, I have a project with a main.scss file that imports several other small stylesheets. My small stylesheets are stored in an includes/ directory. I'd like to be able to watch for changes in includes/ and then recompile main.scss so I could refresh my browser and see the changes without having to switch over the main.scss and save the file.

It's really not a huge issue, but I was hoping to replace a build process like gulp or a tool like [CodeKit](https://incident57.com/codekit/) with your package for simple projects. If that's outside of the scope that you intended for your package, that's totally understandable.

**Comment by armin-pfaeffle** [comment]
Have you checked the [main](https://github.com/armin-pfaeffle/sass-autocompile#main) parameter? For better understanding have a look at the [examples](https://github.com/armin-pfaeffle/sass-autocompile#main-parameter).

[I know, that it's not the best way](https://github.com/armin-pfaeffle/sass-autocompile/issues/56), but this is how my package works at the moment. Probably I will change that behaviour in futures.

**Comment by goronfreeman** [comment]
I completely missed that. Thanks for taking the time to point that out to me. Sorry to take up your time by not reading the README close enough. I'm really enjoying using this package!

**Comment by armin-pfaeffle** [comment]
No Problem. Perhaps I should spend more time on documentation so it's getting clearer what you can do with my package and what not ;)
