### ISSUE TITLE
processes wrong file if autosave is enabled

### ISSUE THREAD

**Issue by ben-page** [armin-pfaeffle/sass-autocompile#60]
I have autosave enabled in Atom. This causes Atom to save your file when ever you switch tabs. But, this is causing sass-autocompile to process the wrong file.

**Example**
If I'm working on a scss file and switch to an html file, Atom saves the scss file. But sass-autocompile attempts to compile the html file instead of the scss file. So I see an error like this:  `Error: Invalid CSS after "": expected 1 selector or at-rule, was "<!doctype html>"` and the css file is not updated.

**Comment by armin-pfaeffle** [comment]
Hey! Thanks for you report. I published a fixed version right now.
