### ISSUE TITLE
Endless loop

### ISSUE THREAD

**Issue by soanvig** [armin-pfaeffle/sass-autocompile#61]
Endless loop (like while(true)) makes whole computer freeze. Is there any solution? Endless loop is easy to create (by mistake of course).

**Comment by armin-pfaeffle** [comment]
Hey! What do mean with that?

**Comment by soanvig** [comment]
When I do endless loop, any kind of endless loop, let's say:
`@while $i > 0 {
  .item-#{$i} { width: 2em * $i; }
  $j: $i - 2;
}`
Here we have typo which causes $i to not change it's value.
This kind of loop freezes my computer. Linux x64 Elementary (Ubuntu), Atom editor.
Maybe there is a solution to stop executing after X seconds?

**Comment by armin-pfaeffle** [comment]
Ah, okay! Yes, you are right! I will have a look at how this feature can be embedded!

**Comment by armin-pfaeffle** [comment]
I published version 0.13.0 right now. It has a [timeout option](https://github.com/armin-pfaeffle/sass-autocompile/#node-sass-execution-timeout) to solve this issue.
