### ISSUE TITLE
../..../node-sass: Not a directory

### ISSUE THREAD

**Issue by Amstramgram** [armin-pfaeffle/sass-autocompile#62]
Hi, i have a error on compilation. Commande failed. When i clicked on "Show details output" i have this:

" /bin/sh: /usr/local/bin/sass/node-sass: Not a directory "

i install node-sass with your command line "sudo npm install node-sass -g".

OSX 10.11.4
Atom 1.6.2
node -v 
v5.10.0
npm -v 
3.8.3
node-sass -v : 
node-sass 3.4.2 (Wrapper) [Javascript]
libsass 3.3.2 (Sass Compiler) [C/C++]
which node-sass
/Users/JulienMiclo/.npm/bin/node-sass
echo "$PATH"
./bin:/usr/local/bin:/usr/local/sbin:/Users/JulienMiclo/.dotfiles/bin:/usr/local/share/npm/bin:/usr/local/bin:/usr/sbin:/sbin:/Users/JulienMiclo/.npm/bin

What have I done wrong?

Thank you.

**Comment by armin-pfaeffle** [comment]
Hey! Have you set option [Path to node-sass command](https://github.com/armin-pfaeffle/sass-autocompile#path-to-node-sass-command? Did this help?

**Comment by Amstramgram** [comment]
Yes, i set this option but i have this error: /bin/sh: /usr/local/bin/node-sass: No such file or directory. Any ideas ?

**Comment by armin-pfaeffle** [comment]
Try these steps:

1. Try to restart Atom. In some cases this works ;)
2. Can you check if there is a `node-sass` executable in `/usr/local/bin`?
3. If not, can you detect where node-sass is installed by entering `which node-sass` in your terminal. Put the path to the [Path to node-sass command](https://github.com/armin-pfaeffle/sass-autocompile#path-to-node-sass-command).

Did this work for you?

**Comment by Amstramgram** [comment]
I fixed my problem, i reinstall osx  ;)

**Comment by armin-pfaeffle** [comment]
WHAT? Why that?

**Comment by Amstramgram** [comment]
Fresh clean space for work who function most correctly. I have too much install nmp, php, mysql, and strange bug in my osx. I know it's not necessary for solve this issue.

Q: It's possible to haven't extra space line between two css line in compiled css file ?

**Comment by armin-pfaeffle** [comment]
> Fresh clean space for work who function most correctly. I have too much install nmp, php, mysql, and strange bug in my osx. I know it's not necessary for solve this issue.
Sounded a lil bit to hardcore ;)

> Q: It's possible to haven't extra space line between two css line in compiled css file ?
Have you tried [these options](https://github.com/armin-pfaeffle/sass-autocompile#compile-with-compressed-output-style) or its [corresponding parameters](https://github.com/armin-pfaeffle/sass-autocompile#compilecompressed)? Try nested or expanded output style.

**Comment by Amstramgram** [comment]
Yes i try 4 compiled style but it's not that.
With compileCompact i have : 
```
body { line-height; 1;}

ol, ul { list-style: none;}

strong { font-weight: 700;}
```
but i would like no space between two lines:
```
body { line-height; 1;}
ol, ul { list-style: none;}
strong { font-weight: 700;}
```

**Comment by armin-pfaeffle** [comment]
Well, my package is only a wrapper for node-sass, so I have no influence on output. The only idea I have is to use an additional package or a manual "empty-line-remover"?!

**Comment by Amstramgram** [comment]
Ok, no problem, thanks again.

**Comment by armin-pfaeffle** [comment]
Is your output for production systems? Or only for development?
