### ISSUE TITLE
spawn cmd.exe ENOENT

### ISSUE THREAD

**Issue by robweighill** [armin-pfaeffle/sass-autocompile#63]
I am having issues with the sass-autocompile.
The compile is triggered on save as it is meant to, however I get the following error:

spawn cmd.exe ENOENT

Google has proved unhelpful in this case, so any help would be appreciated.

**Comment by armin-pfaeffle** [comment]
Hey! Do you have some more information? Can you post exception text?

**Comment by robweighill** [comment]
Hi, unfortunately this is all I get:

![capture](https://cloud.githubusercontent.com/assets/18466213/14677715/a1515c44-070a-11e6-909b-e8bee4f14cfd.PNG)

This is a fresh Atom install, Windows 10, latest Node JS installed, node-sass installed with "-g" option.

**Comment by armin-pfaeffle** [comment]
What system do you use? Win/Mac/Linux? Which version?
Do you have installed node.js and node-sass [as described here](https://github.com/armin-pfaeffle/sass-autocompile#requirements)?
Have you tried restarting Atom/your machine after installing requirements?

**Comment by robweighill** [comment]
As mentioned in the above post I'm on Win10, have installed node.js and node-sass (as described) and have done multiple reboots since installation.

**Comment by armin-pfaeffle** [comment]
Sorry ;) I think I have missed the last line!

I have no idea what the problem can be. I found lot's posts too, but no real solution for this.

Can you execute the following command in Windows console:
```
node-sass --version >nul 2>&1 && (echo found) || (echo fail)
```
What is the output?

**Comment by robweighill** [comment]
Not to worry.
The output from the above is 'found'

![capture](https://cloud.githubusercontent.com/assets/18466213/14706650/ee82d954-07b7-11e6-967c-fa8a61832a3e.PNG)

**Comment by armin-pfaeffle** [comment]
I think you node.js and node-sass installation is fine.

Can you post your %PATH% variable? I found [this thread](https://discuss.atom.io/t/spawn-cmd-exe-enoent/19595/4).

Another idea would be to remove und reinstall my package.

**Comment by robweighill** [comment]
C:\Users\robweighill\AppData\Local\atom\bin;C:\Users\robweighill\AppData\Roaming\npm;C:\Windows\System32

I've just added the System32 as suggested by the post but this makes no difference.

I have also uninstalled and reinstalled your package, but sadly no change.

I will totally strip out my system this afternoon, reinstall atom and only add your package and see if I can get this working.

**Comment by armin-pfaeffle** [comment]
What about your system variable %PATH%? Here is mine:
```C:\ProgramData\Oracle\Java\javapath
C:\Python27\
C:\Python27\Scripts
%SystemRoot%\system32
%SystemRoot%
%SystemRoot%\System32\Wbem
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\
C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static
C:\Program Files\Microsoft\Web Platform Installer\
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
C:\Program Files (x86)\Gtk-Runtime\bin
C:\Program Files\nodejs\
```

**Comment by robweighill** [comment]
Here's my system %PATH%
```
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common; 
C:\Program Files (x86)\Intel\iCLS Client\;
C:\Program Files\Intel\iCLS Client\;
%SystemRoot%\system32;
%SystemRoot%;
%SystemRoot%\System32\Wbem;
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;
C:\Program Files (x86)\Common Files\Lenovo;
C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;
C:\SWTOOLS\ReadyApps;
C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;
C:\Program Files\OpenSSH\bin;
C:\php5;
C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;
C:\Program Files\nodejs\;C:\Windows\System32
```

**Comment by armin-pfaeffle** [comment]
Well, everything seems to be OK for me...

Do you want to test another thing for me ;) Press CTRL+ALT+I in Atom, so Developer Tools are opened. Go to Console tab and execute this:
```
var exec = require('child_process').exec;
var command = 'echo "test"';
exec(command, { env: Object.create(process.env) }, function(a, b, c) {
    console.log(a);
    console.log(b);
    console.log(c);
});
```

**Comment by robweighill** [comment]
This is the output:

![capture](https://cloud.githubusercontent.com/assets/18466213/14709699/fbe52a7c-07c9-11e6-8d4c-f0242773af7a.PNG)

**Comment by armin-pfaeffle** [comment]
And the result of the second code snippet?

**Comment by robweighill** [comment]
There's only one code snippet in your post?

**Comment by armin-pfaeffle** [comment]
I have modified my post before your comment?! You cannot see that?

Here the second snippet:
```
var exec = require('child_process').exec;
var command = 'node-sass --version >nul 2>&1 && (echo found) || (echo fail)';
exec(command, { env: Object.create(process.env) }, function(a, b, c) {
    console.log(a);
    console.log(b);
    console.log(c);
});
```
I don't think that this will work, but can you execute this too?!

Can you try this too?!
```
var exec = require('child_process').exec;
var command = 'node --version';
exec(command, { env: Object.create(process.env) }, function(a, b, c) {
    console.log(a);
    console.log(b);
    console.log(c);
});
```
Sorry for that wild testing...

**Comment by robweighill** [comment]
No to worry, very glad to have some help with this!
(I hadn't refreshed the page so your mod didn't appear - sorry)

Results of the 2nd and 3rd code snippets:

![image](https://cloud.githubusercontent.com/assets/18466213/14710302/c01544f2-07cc-11e6-9872-ffe624d4ff07.png)

**Comment by armin-pfaeffle** [comment]
Thanks!

That was one usage of `child_process` package... It seems everything is okay with your installation so far. Atom can access cmd.exe, node and node-sass without any problems.

Can you modify the file compiler.coffee in `C:\Users\<username>\.atom\packages\sass-autocompile` and replace it with [compiler.txt](https://github.com/armin-pfaeffle/sass-autocompile/files/229984/compiler.txt)? I added some `console.log` commands. So after replacing, open Atom, press CTRL+ALT+I for Developer Tools, compile a SASS file (e.g. by saving it) and show me the output.

**Comment by robweighill** [comment]
As requested:

![image](https://cloud.githubusercontent.com/assets/18466213/14710765/a52785a4-07ce-11e6-981a-261fbc668bd5.png)

**Comment by armin-pfaeffle** [comment]
Haha!!! We found the problem ;) Have a look at the command: `\usr\local\bin\node-sass...`. You are on a Windows machine, so this cannot work!

Please check the options of my package and remove any content in last option [Path to node-sass command](https://github.com/armin-pfaeffle/sass-autocompile#path-to-node-sass-command). Did this help?

When not, open Developer Tools (CTRL+ALT+I) and execute `process.platform`. What is the output?

**Comment by robweighill** [comment]
Ha! This worked a treat, it must have pulled that through when I migrated everything from my Mac.
Thank you so much for the help, sorry it was such a simple mistake on my part.

**Comment by armin-pfaeffle** [comment]
I could have told you that before this long testing process, but I did not think that it's that easy ;) But I'm glad that I could help you and there is no further bug in my package!
