### ISSUE TITLE
Spawn cmd.exe enoent (sass-autocompiler)

### ISSUE THREAD

**Issue by victormorales5449** [armin-pfaeffle/sass-autocompile#65]
This is error after version 1.7, how can i fix this error?

**Comment by armin-pfaeffle** [comment]
Which system do you use? Mac? Linux? Win?

Do you have entered a value in option [Path to node-sass command](https://github.com/armin-pfaeffle/sass-autocompile#path-to-node-sass-command)?

**Comment by victormorales5449** [comment]
I use to windows.


Yes I am the value path to node-sass command

**Comment by armin-pfaeffle** [comment]
Have you installed node-sass globally via `npm install node-sass -g`? Then it's not necessary to set [Path to node-sass command](https://github.com/armin-pfaeffle/sass-autocompile#path-to-node-sass-command). Clear this option and then it should work.
