### ISSUE TITLE
Command failed 

### ISSUE THREAD

**Issue by cawo88** [armin-pfaeffle/sass-autocompile#66]
I get this error when trying to compile on save
'Command failed: /bin/sh -c node-sass --output-style compressed --indent-type space -- indent-width 2 --precision 5 "../path/styles.sass" "../path/styles.css" /bin/sh: node-sass: command not found'

node-sass is installed globally and I have tried the followings...
1. running "apm rebuild-module-cache" 
2. set the path to '/usr/local/bin' under Path to 'node-sass' command under Settings
3. Un-installed and re-installed the package. 

I am using version v0.12.6

**Comment by cawo88** [comment]
issue is solved by re-installing sass globally

**Comment by armin-pfaeffle** [comment]
Good to hear that it works ;)

**Comment by NgKhanh** [comment]
How can set path in window 10 ? pls
