### ISSUE TITLE
Compile partials is ommited

### ISSUE THREAD

**Issue by nahuelhds** [armin-pfaeffle/sass-autocompile#69]
**Atom version:** 1.8.0
**Plugin version:** 0.12.47
**OS:** Windows 10 64 bits

Even having my compile partials **unchecked**, see here:
![image](https://cloud.githubusercontent.com/assets/1885647/15902609/276f868a-2d7f-11e6-850b-d8dd383e8c90.png)

The plugin is compiling when I'm pressing `ctrl+s`

Some extra information:
* My file is inside a subdirectory of my `scss` folder. E.G.: `/path/to/my/project/scss/subfolder/_partial.scss`
* Just in case, I've moved the partial to the parent and happens the same: `/path/to/my/project/scss/_partial.scss`

So I think it's just a bug, or maybe I'm doing something wrong. Any information you need, just let me know.

Of course, this is an excellent package! Congratulations

**Comment by armin-pfaeffle** [comment]
Hey!

Well, I could not reproduce your bug. Do you have a first-line-comment in your partial?

**Comment by nahuelhds** [comment]
Hi! I've finally could solve the problem by uninstalling and re installing the package! Weird but worked.

Thanks for your feedback
