### ISSUE TITLE
Error: Path is not defined - index: undefined, line: undefined, file: undefined

### ISSUE THREAD

**Issue by cperryk** [armin-pfaeffle/sass-autocompile#7]
When saving a .scss file, I'm getting this error:
```
Error: Path is not defined - index: undefined, line: undefined, file: undefined
```

I'm on Mac OSX 10.10.4. Node and node-sass are installed globally. Node-sass is at `/usr/local/bin/node-sass`. My SCSS file has this at the top:
```
// out: test.css
```

I'm on Atom 0.199.0.

I'm seeing this error regardless of how I start Atom — running the `atom` command in terminal or clicking Atom via the Dock and dragging the project folder into it.

**Comment by armin-pfaeffle** [comment]
Thanks for you report! I fixed it. Please try latest version 0.6.5.

**Comment by cperryk** [comment]
That did it! Thanks! And thanks for this package.
