### ISSUE TITLE
SASS-Autocompile: Compilation error || spawn.cmd.exe ENOENT

### ISSUE THREAD

**Issue by phatNguyen93** [armin-pfaeffle/sass-autocompile#70]
Hi admin, 

I tried to compile and export an css file but i ran into this error : spawn.cmd.exe ENOENT

this is my first line: //compileCompressed: C:/Users/Phat/Desktop/Phatty website/Phatty v.2/css/test.css

would you please tell me if i did something wrong?

kind regards,
Phat

**Comment by armin-pfaeffle** [comment]
Hey!

First of all, you should use quotes to ensure, that every works as expected when using spaces in output path:

```
//compileCompressed: "C:/Users/Phat/Desktop/Phatty website/Phatty v.2/css/test.css"
```

Do you have installed node-sass globally (via `npm install node-sass -g`)?
What happens when you open a cmd and execute `node-sass`?
Do you have set [this option](https://github.com/armin-pfaeffle/sass-autocompile#path-to-node-sass-command)? If yes, empty this value.

**Comment by phatNguyen93** [comment]
Hi, 
thank you for reply. 
Yes I had installed node-sass as instructed. My cmd out-put is:

![image](https://cloud.githubusercontent.com/assets/19859645/16011831/5780378a-31ca-11e6-840c-41c1e08a4fe3.png)

My "path to 'node-sass' command" option is empty too

**Comment by armin-pfaeffle** [comment]
Hey!

Can you check [this issue](https://github.com/armin-pfaeffle/sass-autocompile/issues/63) and try the steps I explained there?!

But before, try to uninstall my package and reinstall it.

**Comment by phatNguyen93** [comment]
Hi, I have added the "C:\Windows\System32" into %PATH%. Seem like it working now :) 

Here is the ouput:
![image](https://cloud.githubusercontent.com/assets/19859645/16031040/611d4fa6-323a-11e6-8de2-8ffcd8b3f998.png)

Thank you so much

**Comment by armin-pfaeffle** [comment]
Okay, it seems working! :)

But I don't know why this path has been missing in your %PATH% variable.

**Comment by phatNguyen93** [comment]
lel... I wish I know. Sometime I can't even ping in the cmd ...

**Comment by phatNguyen93** [comment]
Thank you so much :)

**Comment by armin-pfaeffle** [comment]
Now it should work. `PING.EXE` is placed in `C:\Windows\System32`, so your cmd now has access to it.

**Comment by phatNguyen93** [comment]
wow, thank you. 2 birds with one stone :dancer:
