### ISSUE TITLE
Output path

### ISSUE THREAD

**Issue by MrBlaise** [armin-pfaeffle/sass-autocompile#71]
Hey! 

Thanks for this awesome tool! Is there a way to specify an output path for the compiled css instead of putting right next to the *.scss file?

**Comment by armin-pfaeffle** [comment]
Hey!

There is a way! Have a look at [these options](https://github.com/armin-pfaeffle/sass-autocompile#filename-pattern-for-compressed-compiled-files). There you can set a default output path. And when you need a specific path for a project, you can override these options in your SASS/SCSS files.
