### ISSUE TITLE
Error: Invalid CSS

### ISSUE THREAD

**Issue by Warriorsfury** [armin-pfaeffle/sass-autocompile#72]
Hey! Recently switched to Atom purely for this autocompiler, and i'm running into an issue. Whenever I save, I get this error (obviously from the detailed output):

{
  "formatted": "Error: Invalid CSS after \"a {\": expected \"}\", was \"{\"\n        on line 3 of D:/XAMPP/htdocs/sass/style.sass\n>> a { {\n   ---^\n",
  "message": "Invalid CSS after \"a {\": expected \"}\", was \"{\"",
  "column": 4,
  "line": 3,
  "file": "D:/XAMPP/htdocs/sass/style.sass",
  "status": 1
}

----------------------------------------------------------------------------------------------------------------------
If it is any help, here is my sass from my file named "style.sass"

$defaultLinkColor: #46EAC2;

a {
	color: $defaultLinkColor;
}

$wk: -webkit-;

.rounded-box {
  #{$wk}border-radius: 4px;
}

**Comment by Warriorsfury** [comment]
I seem to have fixed it! Saving a file as "style.sass" won't work. Save it as "style.scss"

**Comment by armin-pfaeffle** [comment]
Hey!

Yes, you have to decide which syntax you want to use: SASS or SCSS -- there are two different styles ;)

SCSS:
```scss
$font-stack:    Helvetica, sans-serif;
$primary-color: #333;

body {
  font: 100% $font-stack;
  color: $primary-color;
}
```

SASS
```sass
$font-stack:    Helvetica, sans-serif
$primary-color: #333

body
  font: 100% $font-stack
  color: $primary-color
```

Have a look at the documentation!
