### ISSUE TITLE
An odd issue. Command failed?

### ISSUE THREAD

**Issue by Warriorsfury** [armin-pfaeffle/sass-autocompile#75]
Hey! My autocompile was working, until I recently tried saving I encountered this error, and can't seem to find a fix or fix it myself.

Command failed: cmd.exe /s /c "node-sass --output-style compact --indent-tytpe space --indent-width 2 --precision 5 "D:\XAMPP\htdocs\xG\sass\style.scss" "D:\XAMPP\htdocs\xG\sass\style.compact.css

Any ideas?

**Comment by armin-pfaeffle** [comment]
Hey! Is there only this error message? Did you any updates on node.js? node-sass? What ist the output when you open cmd and execute `node-sass`?

**Comment by Warriorsfury** [comment]
This is the only error message yes. No updates on node.js. No updates on node-sass. The output is:

Providew a sass file to render

Example: Compile foobar.scss to foobar.css
  node-sass --output-style compressed foobar.scss > foobar.css
  cat foobar.scss | node-sass --output-style compressed > foobar.css

Example: Watch the sass directory for changes, compile with sourcemaps to the css directory
  node-sass --watch --recursive --output css
    --source-map true --source-map-contents sass

**Comment by Warriorsfury** [comment]
Anything? Kinda at a loss xD

**Comment by armin-pfaeffle** [comment]
Well, it seems node-sass is installed correctly. I tried the command, you copied above and everything is fine. Are you sure, that there is no quotation mark at the end of the error message?

Can you uninstall and reinstall my package?

**Comment by Warriorsfury** [comment]
I have version 3.8.0 of node-sass, and version 3.3.6 of libsass.

Uninstalling and reinstalling has the same effect, i'll also upload a screenshot of the exact error.

http://image.prntscr.com/image/6698f3508278446fa78382dbe83c1f84.png

**Comment by armin-pfaeffle** [comment]
Well, I have no idea...

Do you have write rights in `D:\XAMPP\htdocs\xG\sass\`?
Can you create a minimal `style.scss` in D:\ and execute compilation?
Can you disable all plugins and try compilation again?

**Comment by Warriorsfury** [comment]
A missing... f**king... semi-colon... 

A missing semi-colon caused me to uninstall / reinstall every plugin I had, had me unlock the normally disabled windows 10 admin account, and give myself full permissions, download Take Ownership, and call upon one of my friends to help me figure out if it was a write permissions error.

Holy. Crap.

Needless to say though... thank you for your help! Haha

**Comment by armin-pfaeffle** [comment]
Great to hear that it's working now ;)
