### ISSUE TITLE
Saving is doing nothing

### ISSUE THREAD

**Issue by vjsevill** [armin-pfaeffle/sass-autocompile#78]
I just got the package after doing the "npm install node-sass -g".  When i execute "which node-sass", i get "/usr/local/bin/node-sass".  It seems like i downloaded it correctly, however when i save in Atom, nothing happens.  What am i missing?

**Comment by armin-pfaeffle** [comment]
Hey!

No notification appears? Restart Atom and try again! Then check you settings! Is the package disabled? Is [Compile on Save](https://github.com/armin-pfaeffle/sass-autocompile#compile-on-save) enabled?

When everything seems to be okay, open developer tools via `View -> Developer -> Toggle Developer Tools` and check if there is any message about sass-autocompile package.

**Comment by vjsevill** [comment]
No notification appears after i restarted Atom.  I checked my packages and I cant even find package "sass-autocompile".  If you want, you can google hangeout w/ me and view my screen

**Comment by armin-pfaeffle** [comment]
Try to reinstall my package?!

**Comment by vjsevill** [comment]
I just re downloaded, quit atom and reopened and tried saving, nothing
happened, and checked my settings and there is no sass autocomplete
package.[image:
Inline image 1]

[image: Inline image 2]

**Comment by armin-pfaeffle** [comment]
But you definitly installed sass-autocompile package in Atom? (Settings -> Install)

That sounds a lil' bit strange too me. Do you have rights to install a package? I never heard about such a problem.

PS: Your images are not visible!

**Comment by vjsevill** [comment]
Resolved. Strange, the package never appeared in the settings window until today.  Anyways, thanks!

**Comment by armin-pfaeffle** [comment]
Hm... Probably an Atom bug?
