### ISSUE TITLE
.gitignore .sass-cache preventing auto compiling

### ISSUE THREAD

**Issue by DarthOstrich** [armin-pfaeffle/sass-autocompile#80]
I had .sass-cache listed in my ".gitignore" and the auto-compile stopped working. I took it out of the ".gitignore" file and it worked again. Is this a local issue, or something else?

**Comment by armin-pfaeffle** [comment]
I tested a minimal example and your .gitignore entry had no influence on auto-compilation. Here everything is working fine!

I think it's probably a local thing. I suggest, that you disable all your other packges, try it again and enable one package after each other.

**Comment by DarthOstrich** [comment]
Will do. Thank you for looking into it anyways!
