### ISSUE TITLE
Error message underscores (_) displays as dashes (-)

### ISSUE THREAD

**Issue by Bubbi** [armin-pfaeffle/sass-autocompile#81]
If an error occurs in a compilation, for example if a scss variable is referenced that doesn't exist, then an error message is shown about this. This is all great, but if a scss variable uses underscores (_), then the error message somehow changes these to dash (-) in the detailed output panel. At least it looks like it is dashes.

So for the variable reference:
`$c__red`
it somehow changes it to:
`$c--red`

So the entire error message looks like this:

**Error: Undefined variable: "$c--red".**

![atom-sass-autocompile-error-message](https://cloud.githubusercontent.com/assets/863630/17507891/7a7e5ffe-5e12-11e6-8ed9-991c7435280f.jpg)

It is still possible to just use the filename and line-number to identify the actual scss variable name, but it should still display the correct variable in my mind :-)

**Comment by armin-pfaeffle** [comment]
Hey! Thanks for your report! But that's not an issue of my package, it's node-sass that replaces the underscrore. Have a look at my terminal output. The underscore is replaced there too.
```
$ node-sass main.sass main.css
{
  "formatted": "Error: Undefined variable: \"$c--red\".\n        on line 11 of main.sass\n>>   color: $c__red;\n   ---------^\n",
  "message": "Undefined variable: \"$c--red\".",
  "column": 10,
  "line": 11,
  "file": "C:/Users/Armin/.atom/packages/sass-autocompile/test/main.sass",
  "status": 1
}
```
I found [this issue](https://github.com/sass/sass/issues/334) about that (in my opinion) strange behaviour.

**Comment by esr360** [comment]
@armin-pfaeffle I agree it is indeed strange behaviour. Feel free to "like" any comments on the issue which question the behaviour, I'd like to see it changed.

**Comment by udaypathak** [comment]
/* Error: expected ":".
 *   ,
 * 1 | $primary - font:Roboto, sans - serif; 
 *   |          ^
 *   '
 *   scss\style.scss 1:10  root stylesheet */

body::before {
  font-family: "Source Code Pro", "SF Mono", Monaco, Inconsolata, "Fira Mono",
      "Droid Sans Mono", monospace, monospace;
  white-space: pre;
  display: block;
  padding: 1em;
  margin-bottom: 1em;
  border-bottom: 2px solid black;
  content: 'Error: expected ":".\a   \2577 \a 1 \2502  $primary - font:Roboto, sans - serif; \d\a   \2502           ^\a   \2575 \a   scss\\style.scss 1:10  root stylesheet';
}


why getting compile error in SASS when using hypen in variable $primary-font?
