### ISSUE TITLE
sass-autocompile 

### ISSUE THREAD

**Issue by webyuga** [armin-pfaeffle/sass-autocompile#82]
![error](https://cloud.githubusercontent.com/assets/2657796/17551055/af5a9310-5f15-11e6-9dc4-68d970f73dc8.png)

Hi All,
I am trying to compile my simple .scss file on atom but it fails compiling with the message node-sass is not recognized. I have installed node.js & node-sass through command prompt. 

Attached screenshot for your reference.

Any help would be much appreciated. TIA.

Regards

**Comment by webyuga** [comment]
I also tried creating the style.nested.css in the project folder with no help.

**Comment by armin-pfaeffle** [comment]
Did you install node-sass *globally* via `npm install -g node-sass`?

**Comment by webyuga** [comment]
Hey, That helped.. Its work fine.. Thanks a lot @ armin
