### ISSUE TITLE
Error when saving scss

### ISSUE THREAD

**Issue by syed-hateem** [armin-pfaeffle/sass-autocompile#83]
'node-sass' is not recognized as an internal or external command,
operable program or batch **file.

This is the error i get when i save scss file using ctrl+shift+c shortcut
my sass version is 3.4.22
also dont know if its related while using prepros to compile scss, my css file doesnt replace variables

**Comment by shahjehanali1** [comment]
i'm also have same erro

**Comment by armin-pfaeffle** [comment]
Have yo installes node-sass globally via `npm install -g node-sass`? (-g parameter is important here!)

Your error message has nothing to do with Prepros, I think.

**Comment by shahjehanali1** [comment]
@armin-pfaeffle its working thanks you are time saver :)

**Comment by armin-pfaeffle** [comment]
I hope it works for @syed-hateem too?!

**Comment by syed-hateem** [comment]
turns out i was not connecting my compiled css file to html
sorry for the trouble 
i thought my browser will read my scss file turns out it cant 
u learn something new everyday :)

**Comment by armin-pfaeffle** [comment]
Ok, great that it works :)
