### ISSUE TITLE
Save main sass file when saving imported files

### ISSUE THREAD

**Issue by PavSidhu** [armin-pfaeffle/sass-autocompile#84]
When using a common Sass structure of having one `main.sass` file which imports all other sass files, it can be tedious when editing an imported file since you must save that file, then save `main.sass` as well so that it can compile everything. 

What would be easier is if when saving an imported file, `main.sass` will be saved and then the Sass will be compiled. I looked through the readme and didn't find any way of doing this. Did I miss something or is there a workaround available? Thanks.

**Comment by PavSidhu** [comment]
Apologies I found the solution in the docs, must have missed it: https://atom.io/packages/sass-autocompile

**Comment by armin-pfaeffle** [comment]
Great ;)
