### ISSUE TITLE
First line choose the output file path

### ISSUE THREAD

**Issue by Quilljou** [armin-pfaeffle/sass-autocompile#87]
Hi, Thank for your great plugin;
And I know in the setting there is a select which I can choose which file is going to compile. and one of them is only with first-line-comment
Is it possible to specify the comment content for the compiled file path , I think it's more flexible , just like autocompiler-jade does;

**Comment by armin-pfaeffle** [comment]
Hey! What exactly do you mean? Can you give me an example?!

**Comment by Quilljou** [comment]
Sorry
I mean like a package called jade-autocompile, when I want to compile  my jade file, I will comment like this
```
// output: ../html/index.html
```
so I can specify where to keep my compiled file,I know in your package setting ,It can choose an output file path,but I always change the destination path,so it's a little inconvenient
Is it clear? Forgive my poor English!

**Comment by armin-pfaeffle** [comment]
Ah, okay. Have a look at the [first-line parameters](https://github.com/armin-pfaeffle/sass-autocompile#parameters). There you can find the [compilation type parameters](https://github.com/armin-pfaeffle/sass-autocompile#compilecompressed) and the [filename patterns](https://github.com/armin-pfaeffle/sass-autocompile#compressedfilenamepattern). Read both sections.

**Comment by Quilljou** [comment]
My fault, You made a great plugin and a detailed documentation,

**Comment by armin-pfaeffle** [comment]
Well, perhaps I should write a short version with som examples. My documentation is a lil' bit too much to read...

**Comment by Quilljou** [comment]
It's not your fault,Perhaps,TL;DR ,people like me are impatient
