### ISSUE TITLE
Command Failed (SASS-Autocompile: Compilation error)

### ISSUE THREAD

**Issue by BosEriko** [armin-pfaeffle/sass-autocompile#88]
What am I doing wrong? This pops up.

```
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: %1 is not a valid Win32 application.

\\?\C:\Users\reyes\AppData\Roaming\npm\node_modules\node-sass\vendor\win32-x64-46\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\reyes\AppData\Roaming\npm\node_modules\node-sass\lib\index.js:24:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

```

**Comment by armin-pfaeffle** [comment]
Hey!

Well, that's a good question. I don't think that it has something to do with my package. Perhaps you try to remove und reinstall node-sass?

What is the output when you open cmd.exe and execute `node-sass`?

**Comment by BosEriko** [comment]
Just tried it on cmd.exe. Same result. D: It wasn't like this yesterday. I also tried reinstalling it. Same result. Seems like it wasn't your package after all. Any ideas how I can fix this? If not, it's okay.

**Comment by armin-pfaeffle** [comment]
What ist the output of these commands? `node --version` and `npm --version`

Perhaps you can try to remove and reinstall nodejs. After that reinstall node-sass via `npm install node-sass -g`. I think that something is broken.

**Comment by BosEriko** [comment]
I did what you said and it works fine now! Great! Thank you very much! And it was such a fast answer, too! :D You're awesome!

**Comment by armin-pfaeffle** [comment]
That's interessting... I tried to install node-sass in my Mac VM. The installation seems to fail because it hangs at `node scripts/install.js`. I tried to execute `node-sass` in terminal and got nearly the same error message.
