### ISSUE TITLE
Compressing output CSS unnecessarily

### ISSUE THREAD

**Issue by csernikmarton** [armin-pfaeffle/sass-autocompile#9]
Hey!

I ran into a problem that I consider being a bug, but let me know your thoughts.

In the general settings I have all the checkboxes unticked, except for 'Enabled', of course. 
I have the following settings locally in a scss file:

```
// out: ../out.css, compress: false, sourceMap: true
```

The problem is that when I have the 'compress' parameter within that line, the output file is being compressed – even though it's value is false. When I remove that parameter completely, I get an uncompressed output which is the expected behaviour because the 'Compress' general setting is unset.

I've been playing only with the 'compress' and 'sourceMap' settings, the first one is having this problem, the latter one doesn't seem to be affected, it works as expected.

I'm working on OS X 10.10.4, Atom 1.0.2, plugin version 0.7.1

Let me know what you think.
Cheers!

**Comment by armin-pfaeffle** [comment]
Hey!

Yes, it was a bug! I fixed it with version 0.7.2, that I published right now.
