### ISSUE TITLE
Saving from a partial SCSS file that has variables gives error

### ISSUE THREAD

**Issue by greenuns** [armin-pfaeffle/sass-autocompile#90]
Hello,
Whenever I try to save from a partial SCSS file the package gives me an error and I would have to go to the main SCSS file and save from there.

For example,
style.scss file imports _variables.scss and _ui.scss.
Both style.scss and _ui.scss use variables from _variables.scss.
If I make a change to _ui.scss and save from there the package gives an "Undefined variable" error.
But if switch tab and save from style.scss, everything compiles.

Is there an option that I am missing? or would this be in the next version?

thank you

**Comment by armin-pfaeffle** [comment]
Hey!

Have a look at the [main](https://github.com/armin-pfaeffle/sass-autocompile#main) parameter.

If you want to compile style.css when you save _ui.scss you should setup this comment as first line-comment:
```
// main: ../relative/path/to/style.css
```
Clear?
