### ISSUE TITLE
How to change default OUTPUT path

### ISSUE THREAD

**Issue by yareckk** [armin-pfaeffle/sass-autocompile#91]
Hello,
This is definitely a newbie question ;)
How could I change the output path? The default one is the same as an input but I'd like to change it this way:
INPUT -  /scss/style.scss
OUTPUT - /stylesheet/style.css
I do not see any options for it. Should I change any config files?

**Comment by armin-pfaeffle** [comment]
Welcome!

This is really easy: use a relative path. In your example you have to add this first-line-comment top `style.css`:
```
// compileCompressed: ../stylesheet/style.css
```
... or better:
```
// compileCompressed: ../stylesheet/$1.min.css
```
In the second example `$1` is replaced by the filename or the SCSS file, in this case by `style`. This is more flexible then setting a fixed filename.

**Comment by yareckk** [comment]
Amazingly easy! Works perfectly! Thank you!
