### ISSUE TITLE
Autocompile not working after updated to latest version 

### ISSUE THREAD

**Issue by AshHoe** [armin-pfaeffle/sass-autocompile#93]
I received an update notification of SASS Autocompile last night and updated it, when I opened it today it says that there's an issues with the Atom version so I've updated to the latest Atom and it's still showing this error message every time I save my sass. Is there any way that could solve this issues? Thanks. 

![screen shot 2016-10-12 at 1 17 20 pm](https://cloud.githubusercontent.com/assets/22785122/19298217/88b4c61e-907e-11e6-83f6-776d4460415e.png)

**Comment by armin-pfaeffle** [comment]
After the update to 1.11.1 on my Windows machine, everything is working fine.

Do you use a Mac OS? Can you provide me the full stack trace?

**Comment by AshHoe** [comment]
@armin-pfaeffle  Yes I'm using a Mac OS. 

Uncaught TypeError: Cannot read property 'file' of null
/Users/ash/.atom/packages/sass-autocompile/lib/sass-autocompile-view.coffee:143

TypeError: Cannot read property 'file' of null
    at SassAutocompileView.module.exports.SassAutocompileView.erroneousCompilation (/Users/ash/.atom/packages/sass-autocompile/lib/sass-autocompile-view.coffee:143:24)
    at /Users/ash/.atom/packages/sass-autocompile/lib/sass-autocompile.coffee:451:34
    at Function.module.exports.Emitter.simpleDispatch (/Users/ash/.atom/packages/sass-autocompile/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/ash/.atom/packages/sass-autocompile/node_modules/event-kit/lib/emitter.js:125:28)
    at NodeSassCompiler.module.exports.NodeSassCompiler.onCompiled (/Users/ash/.atom/packages/sass-autocompile/lib/compiler.coffee:602:26)
    at /Users/ash/.atom/packages/sass-autocompile/lib/compiler.coffee:563:30
    at /Users/ash/.atom/packages/sass-autocompile/lib/compiler.coffee:469:21
    at /Users/ash/.atom/packages/sass-autocompile/lib/compiler.coffee:489:21
    at ChildProcess.exithandler (child_process.js:205:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)

**Comment by armin-pfaeffle** [comment]
Can you try to remove und reinstall my package?

I tested current version with Windows and Mac OS, based on Atom 1.11.1. Everything is fine here.

**Comment by AshHoe** [comment]
@armin-pfaeffle It's still not working and showing the same stack trace after I've reinstalled the package.

**Comment by AshHoe** [comment]
I've recently updated my OS to macOS Sierra(before updating your package),
could it be the problem? Because it's not working.

**Comment by armin-pfaeffle** [comment]
Sorry for my late answer! Having a lot to do at the moment!

- Can you execute `node-sass` in terminal? What is the output?
- Execute `which node-sass` which outputs the path of node-sass executable. When you installed node-sass **globally** then it should be `/usr/local/bin`.
- Set this path to [Path to node-sass command] option in sass-autocompile settings and retry compiling a SASS file

The problem here is that node-sass is not accessable and so compilation fails. I don't know why it worked before.

**Comment by AshHoe** [comment]
- This is the output that I've got when I've executed `node-sass` in terminal: 

```
Provide a Sass file to render

Example: Compile foobar.scss to foobar.css

  node-sass --output-style compressed foobar.scss > foobar.css

  cat foobar.scss | node-sass --output-style compressed > foobar.css


Example: Watch the sass directory for changes, compile with sourcemaps to the css directory

  node-sass --watch --recursive --output css

    --source-map true --source-map-contents sass
```

- Yes the path is correct.

- I couldn't find any settings button in my sass-autocompile package. 
 
![screen shot 2016-10-19 at 11 27 22 am](https://cloud.githubusercontent.com/assets/22785122/19504728/24ee1704-95ef-11e6-9961-37c64be43f7e.png)

**Comment by armin-pfaeffle** [comment]
Well, it seems that something went wrong while installation. There must be a settings button. Unintsall and reinstall my package again. Sorry for that, but that's not a problem of my packages.

**Comment by AshHoe** [comment]
Okay, thanks a lot for your help! :) The package suddenly worked again when
I was using my Atom today.

**Comment by armin-pfaeffle** [comment]
That's a lil bit strange... Did you restart Atom before?
