### ISSUE TITLE
Compact Style Add line break on every line

### ISSUE THREAD

**Issue by afmarchetti** [armin-pfaeffle/sass-autocompile#96]
<img width="449" alt="schermata 2016-10-18 alle 23 26 35" src="https://cloud.githubusercontent.com/assets/8080212/19496986/5a4eb4fe-958a-11e6-86b3-d195c7741bad.png">
<img width="509" alt="schermata 2016-10-18 alle 23 26 40" src="https://cloud.githubusercontent.com/assets/8080212/19496987/5b8e755c-958a-11e6-91a7-225572780496.png">

What i can do?  maybe i do something wrong?

**Comment by armin-pfaeffle** [comment]
Hey! Sorry, but these empty lines are added by node-sass. I haven't found any option to disable that.

**Comment by afmarchetti** [comment]
mmmm bad news...

**Comment by afmarchetti** [comment]
I read lot on node-sass docs but no one had the same problem..

**Comment by armin-pfaeffle** [comment]
Well, I could add an option for removing empty lines. But then, every empty line is deleted?!

**Comment by afmarchetti** [comment]
Like sass the  documentation say the correct logic would be: 

"Nested rules are placed next to each other with no newline, while separate groups of rules have newlines between them" 

http://sass-lang.com/documentation/file.SASS_REFERENCE.html#_15

**Comment by armin-pfaeffle** [comment]
But I'm not the author of node-sass ;) You should create an issue [here](https://github.com/sass/node-sass/issues)

**Comment by afmarchetti** [comment]
Ok many thanks for your amazing job!
