### ISSUE TITLE
Compile to file stopped working (?)

### ISSUE THREAD

**Issue by eminos** [armin-pfaeffle/sass-autocompile#98]
After updating to Atom 1.13.0-beta3 sass-autocompile (0.13.1) "Compile to file" stopped working. Nothing happens when running that command. "Compile direct" still works fine.

**Comment by armin-pfaeffle** [comment]
Can you open Developer Tools (View -> Developer -> Toggle Developer Tools) and use "Compile to file"? Perhaps an error occurs which is printed to console, but normally my package should show an exception then...

**Comment by eminos** [comment]
Nope. No errors in the Console.
But the Deprecation Cop in Atom is reporting this for sass-autocompile:

Argument to path.extname must be a string

Object.extname - C:\Users\emin\AppData\Local\atom\app-1.13.0-beta3\resources\app.asar\src\electron-shims.js:20:10
Function.hasFileExtension - C:\Users\emin\.atom\packages\sass-autocompile\lib\helper\file.coffee:149:28
Object.isSassFile - C:\Users\emin\.atom\packages\sass-autocompile\lib\sass-autocompile.coffee:508:19
Object.compileToFile - C:\Users\emin\.atom\packages\sass-autocompile\lib\sass-autocompile.coffee:395:16
atom-workspace.subscriptions.add.atom.commands.add.sass-autocompile:compile-to-file - C:\Users\emin\.atom\packages\sass-autocompile\lib\sass-autocompile.coffee:311:26
CommandRegistry.handleCommandEvent - C:\Users\emin\AppData\Local\atom\app-1.13.0-beta3\resources\app.asar\src\command-registry.js:259:29

**Comment by armin-pfaeffle** [comment]
Thanks for your report. I will have a closer look to that! I suppose that this is the problem!

**Comment by armin-pfaeffle** [comment]
I fixed the bug with version 0.13.2
